### ISSUE TITLE
Impossible to add custom BeanSerializer with BeanSerializerModifier

### ISSUE THREAD

**Issue by 5kilodope** [FasterXML/jackson-dataformat-xml#102]
I try to define a custom BeanSerializer by using a BeanSerializerModifier. But any custom BeanSerializer is afterwards wrapped by the "XmlBeanSerializerModifier". Therefore the override methods in the custom BeanSerializer will never be called, which makes it unusable. See the following Code from "XmlBeanSerializerModifier" that does the wrapping:

```
    @Override
    public JsonSerializer<?> modifySerializer(SerializationConfig config,
            BeanDescription beanDesc, JsonSerializer<?> serializer)
    {
        /* First things first: we can only handle real BeanSerializers; question
         * is, what to do if it's not one: throw exception or bail out?
         * For now let's do latter.
         */
        if (!(serializer instanceof BeanSerializerBase)) {
            return serializer;
        }
        return new XmlBeanSerializer((BeanSerializerBase) serializer);
    }
```

Is there any way to define a custom BeanSerializer without having the XmlBeanSerializerModifier wrapping it ?

**Comment by cowtowncoder** [comment]
Closing as there is no additional information on functionality desired.
