### ISSUE TITLE
Missing data in nested Lists, deserialization

### ISSUE THREAD

**Issue by viordanov** [FasterXML/jackson-dataformat-xml#112]
Exception occurs while deserialize XML produced for the followed structure:

```
public final class BarcodeControl {
  @JacksonXmlElementWrapper(localName = "Barcodes", useWrapping = true)
  @JsonProperty("Barcode")
  public List<Barcode> barcodes;

  public List<Barcode> getBarcodes() {
      return barcodes;
  }
}

public class Barcode {
  @JacksonXmlElementWrapper(localName = "Lines", useWrapping = true)
  @JsonProperty("Line")
  public List<Line> lines;
}

public class Line {
  public int value;
  public String description;
}
```

The exception is 

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Line"
```

This issue is similar to https://github.com/FasterXML/jackson-dataformat-xml/issues/55 but affects the nested wrapped lists (not root).

**Comment by hobo212** [comment]
i get the same error:
xml:<?xml version="1.0" encoding="UTF-8"?><service><SysHead><SvcCd>30013000001</SvcCd><ScnCd>16</ScnCd><CnsmrSysNo>301400</CnsmrSysNo><CnsmrSrlNo>1505286940657</CnsmrSrlNo><TxnDt>20170913</TxnDt><TxnTm></TxnTm><PvdrSrlNo></PvdrSrlNo><RetSt>S</RetSt><array><RetInfArry><RetCd>000000</RetCd><RetMsg>交易成功</RetMsg></RetInfArry></array><OrgnlCnsmrSvcNo>0000</OrgnlCnsmrSvcNo><MACVal>0000000000000000</MACVal><MACFctr></MACFctr><PINSd>258770420475</PINSd><PrtyLvl></PrtyLvl><VerfFlg>0</VerfFlg><SecretKeyVerNo>0</SecretKeyVerNo><SysRsrv>0</SysRsrv></SysHead><AppHead></AppHead><LocalHead><InfEndFlg>1</InfEndFlg><MsgSeqNo>12288</MsgSeqNo><LkgTxnCd></LkgTxnCd><ErrTxnSeqNo>0</ErrTxnSeqNo><array></array><array></array></LocalHead></service>
java:
package cn.bunuo.scf.adapter.guiyangbank.client.common.response;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;

public class ResponseSysHead {
	private String SvcCd;// 服务代码 String(15) SysHead Y
	private String ScnCd;// 场景代码 String(2) SysHead Y
	private String CnsmrSysNo;// 消费方系统编号 String(6) SysHead Y
	private String CnsmrSrlNo;// 消费方流水号 String(52) SysHead Y
	private String GlblSrlNo;// 全局流水号 String(52) SysHead Y
	private String TxnDt;// 交易日期 String(8) SysHead Y
	private String TxnTm;// 交易时间 String(6) SysHead Y
	private String PvdrSysNo;// 提供方系统编号 String(6) SysHead Y
	private String PvdrSrlNo;// 提供方流水号 String(52) SysHead Y
	private String RetSt;// 返回状态 String(10) SysHead Y
	@JacksonXmlElementWrapper(localName = "array")
	@JsonProperty("RetInfArry")
	private List<ResponseRetInf> RetInfArry;// 返回信息数组 Array SysHead Y
	private String RetCd;// 返回代码 String(32) SysHead Y
	private String RetMsg;// 返回信息 String(100) SysHead Y
	private String OrgnlCnsmrSysNo;// 原始消费方系统编号 String(6) SysHead N
	private String OrgnlTmlIdNo;// 原始终端标识号 String(30) SysHead N
	private String TmlIdNo;// 终端标识号 String(30) SysHead N
	private String OrgnlCnsmrSvcNo;// 原始消费方服务器编号 String(30) SysHead N
	private String CnsmrSvcNo;// 消费方服务器编号 String(30) SysHead N
	private String PvdrSvcNo;// 提供方服务器编号 String(30) SysHead N
	private String UsrLng;// 用户语言 String(20) SysHead N
	private String FileFlg;// 文件标志 String(1) SysHead N
	private String MACVal;// MAC值 String(16) SysHead N
	private String MACFctr;// MAC因子 String(30) SysHead N
	private String PINSd;// PIN种子 String(16) SysHead N
	private String SvcVerNo;// 服务版本号 String(10) SysHead N
	private String PrtyLvl;// 优先级别 String(2) SysHead N
	private String VerfFlg;// 校验标志 String(1) SysHead N
	private String SecretKeyVerNo;// 密钥版本号 String(10) SysHead N
	private String SysRsrv;// 系统保留 String(20) SysHead N
	public String getSvcCd() {
		return SvcCd;
	}
	public void setSvcCd(String svcCd) {
		SvcCd = svcCd;
	}
	public String getScnCd() {
		return ScnCd;
	}
	public void setScnCd(String scnCd) {
		ScnCd = scnCd;
	}
	public String getCnsmrSysNo() {
		return CnsmrSysNo;
	}
	public void setCnsmrSysNo(String cnsmrSysNo) {
		CnsmrSysNo = cnsmrSysNo;
	}
	public String getCnsmrSrlNo() {
		return CnsmrSrlNo;
	}
	public void setCnsmrSrlNo(String cnsmrSrlNo) {
		CnsmrSrlNo = cnsmrSrlNo;
	}
	public String getGlblSrlNo() {
		return GlblSrlNo;
	}
	public void setGlblSrlNo(String glblSrlNo) {
		GlblSrlNo = glblSrlNo;
	}
	public String getTxnDt() {
		return TxnDt;
	}
	public void setTxnDt(String txnDt) {
		TxnDt = txnDt;
	}
	public String getTxnTm() {
		return TxnTm;
	}
	public void setTxnTm(String txnTm) {
		TxnTm = txnTm;
	}
	public String getPvdrSysNo() {
		return PvdrSysNo;
	}
	public void setPvdrSysNo(String pvdrSysNo) {
		PvdrSysNo = pvdrSysNo;
	}
	public String getPvdrSrlNo() {
		return PvdrSrlNo;
	}
	public void setPvdrSrlNo(String pvdrSrlNo) {
		PvdrSrlNo = pvdrSrlNo;
	}
	public String getRetSt() {
		return RetSt;
	}
	public void setRetSt(String retSt) {
		RetSt = retSt;
	}
	public List<ResponseRetInf> getRetInfArry() {
		return RetInfArry;
	}
	public void setRetInfArry(List<ResponseRetInf> retInfArry) {
		RetInfArry = retInfArry;
	}
	public String getRetCd() {
		return RetCd;
	}
	public void setRetCd(String retCd) {
		RetCd = retCd;
	}
	public String getRetMsg() {
		return RetMsg;
	}
	public void setRetMsg(String retMsg) {
		RetMsg = retMsg;
	}
	public String getOrgnlCnsmrSysNo() {
		return OrgnlCnsmrSysNo;
	}
	public void setOrgnlCnsmrSysNo(String orgnlCnsmrSysNo) {
		OrgnlCnsmrSysNo = orgnlCnsmrSysNo;
	}
	public String getOrgnlTmlIdNo() {
		return OrgnlTmlIdNo;
	}
	public void setOrgnlTmlIdNo(String orgnlTmlIdNo) {
		OrgnlTmlIdNo = orgnlTmlIdNo;
	}
	public String getTmlIdNo() {
		return TmlIdNo;
	}
	public void setTmlIdNo(String tmlIdNo) {
		TmlIdNo = tmlIdNo;
	}
	public String getOrgnlCnsmrSvcNo() {
		return OrgnlCnsmrSvcNo;
	}
	public void setOrgnlCnsmrSvcNo(String orgnlCnsmrSvcNo) {
		OrgnlCnsmrSvcNo = orgnlCnsmrSvcNo;
	}
	public String getCnsmrSvcNo() {
		return CnsmrSvcNo;
	}
	public void setCnsmrSvcNo(String cnsmrSvcNo) {
		CnsmrSvcNo = cnsmrSvcNo;
	}
	public String getPvdrSvcNo() {
		return PvdrSvcNo;
	}
	public void setPvdrSvcNo(String pvdrSvcNo) {
		PvdrSvcNo = pvdrSvcNo;
	}
	public String getUsrLng() {
		return UsrLng;
	}
	public void setUsrLng(String usrLng) {
		UsrLng = usrLng;
	}
	public String getFileFlg() {
		return FileFlg;
	}
	public void setFileFlg(String fileFlg) {
		FileFlg = fileFlg;
	}
	public String getMACVal() {
		return MACVal;
	}
	public void setMACVal(String mACVal) {
		MACVal = mACVal;
	}
	public String getMACFctr() {
		return MACFctr;
	}
	public void setMACFctr(String mACFctr) {
		MACFctr = mACFctr;
	}
	public String getPINSd() {
		return PINSd;
	}
	public void setPINSd(String pINSd) {
		PINSd = pINSd;
	}
	public String getSvcVerNo() {
		return SvcVerNo;
	}
	public void setSvcVerNo(String svcVerNo) {
		SvcVerNo = svcVerNo;
	}
	public String getPrtyLvl() {
		return PrtyLvl;
	}
	public void setPrtyLvl(String prtyLvl) {
		PrtyLvl = prtyLvl;
	}
	public String getVerfFlg() {
		return VerfFlg;
	}
	public void setVerfFlg(String verfFlg) {
		VerfFlg = verfFlg;
	}
	public String getSecretKeyVerNo() {
		return SecretKeyVerNo;
	}
	public void setSecretKeyVerNo(String secretKeyVerNo) {
		SecretKeyVerNo = secretKeyVerNo;
	}
	public String getSysRsrv() {
		return SysRsrv;
	}
	public void setSysRsrv(String sysRsrv) {
		SysRsrv = sysRsrv;
	}
}
my jackson verssion is 2.8.9
