### ISSUE TITLE
Array deserealization from xml

### ISSUE THREAD

**Issue by igorgnedish** [FasterXML/jackson-dataformat-xml#122]
Hi guys,

I've faced with strange issue, could you please help me with this.
I have following xml:
`               <product>`
`               	<externalId>product_key_value</externalId>`
`			<title>test_title_value</title>`
`			<array>`
`				<item><id>1</id></item>`
`				<item><id>2</id></item>`
`			</array>`
`		</product>`

and following code which deserealizes it:
`XmlMapper mapper = new XmlMapper();`
`JsonNode node = mapper.readTree(value);`

and after that node contains following array representation:
`"array":{"item":{"id":"2"}}`

which seems incorrect.
Note that when I performing deserealization like
`mapper.readValue(value, clazz);`
where clazz is a `Class<MyTypeWithArray>` everything works like a charm.

**Comment by masoudlotfi** [comment]
so what is the solution?

**Comment by igorgnedish** [comment]
I wrote my own array detection stuff :-) may share solution but have to find out it first :) it was long time ago.
