### ISSUE TITLE
Text not deserialized when there are other embedded nodes

### ISSUE THREAD

**Issue by aborg0** [FasterXML/jackson-dataformat-xml#123]
Probably this is more like a forum question than a bug, but might be the latter too.
Assume you have the following xml as input (I know this is not a best practice, though I think it is syntactically valid):

    <apple color="red">juicy<qnt>1</qnt></apple>

It will be converted to:

    {
       "apple" : {
         "color" : "red",
         "qnt" : "1"
       }
    }

which leaves out "juicy". I would expect something like this:

    {
       "apple" : {
         "color" : "red",
         "" : "juicy",
         "qnt" : "1"
       }
    }

I know this way a lot of white space will be put to the json output if the xml was pretty-printed, but probably there could be an option to trim whitespaces and only emit text nodes if there is a non-empty content.

**Comment by cowtowncoder** [comment]
Since there is no concrete work item here, I'll close it: I am not opposed to opening something that specifically requests support for "XML mixed content", although there may already be an issue or two for that. If not, may be filed, can add link to this issue as background.

**Comment by aborg0** [comment]
Here is an alternative representation:

    {
       "apple" : {
         "color" : "red",
         "" : [
            "juicy",
            {
               "qnt" : "1"
            }
         ]
       }
    }

This way it can handle mixed content keeping their order and all of its information. (Sorry, I could not find another issue for this. In case you like this representation, I can create a new issue.)
Thanks
PS: `"qnt": "1"` could also be (assuming texts are always represented as they were also part of a possible mixed content): `"qnt": {"": ["1"]}`.

**Comment by cowtowncoder** [comment]
Yes, a new issue would make sense. I will have to say, however, that I am not sure I like the idea of magic names. There are further issues with the differences between ordering in JSON (Object property ordering is undefined) and XML (order is strictly defined, except for attributes....).
But these can be discussed on new issue that targets some level of support for mixed-content for Tree Model.
