### ISSUE TITLE
Sub type with wrapper fails to deserialize

### ISSUE THREAD

**Issue by splatch** [FasterXML/jackson-dataformat-xml#125]
Jackson xml binding fails to deserialize XML if it has conditional wrapper on top of it.

My service provider forces me to handle following situation:

``` xml
<response version="4.0">
    <profile cmd="list" result="ok">
        <items>
            <item>
                <name>X</name>
            </item>
        </items>
    </profile>
</response>
```

At same time profile element might look like this:

``` xml
<response version="4.0">
    <profile cmd="list" result="ok">
        <error code="100">
            <message>Message foo</message>
        </error>
    </profile>
</response>
```

I use sub type with base class for Profile, however error I am getting while traversing stream is:
`Can not deserialize instance of java.util.ArrayList out of START_OBJECT token`

**Comment by cowtowncoder** [comment]
Would need a reproduction here, as well as verification this is still a problem. Closing for now, may be reopened with reproduction (ideally unit test).

**Comment by splatch** [comment]
Thanks for closing it up. I can't remember now how I solved problem, I believe I somehow managed to work it around. It is definitely a good candidate to close.

**Comment by cowtowncoder** [comment]
It is a tricky problem to solve without some sort of help from object model, but I know that content like this exists esp. when data model was not designed with object-binding in mind (or was accessed from loosely-typed language).
