### ISSUE TITLE
empty json field name when xml node has attributes

### ISSUE THREAD

**Issue by herau** [FasterXML/jackson-dataformat-xml#127]
When i'm trying to read an xml like :

```xml
<toto>
    <tata>toto</tata>
    <foo bar="youhou">nodeValue</foo>
</toto>
```

```Java
new XmlMapper().readTree(xmlStream);
```

the result is : 

```Json
{"tata":"toto","foo":{"bar":"youhou","":"nodeValue"}}
```

with jettison i have this result : 

```Json
{"tata":"toto","foo":{"@bar":"youhou","$": "nodeValue"}}
```

**Comment by cowtowncoder** [comment]
Yes, `XmlMapper.setXMLTextElementName(...)` allows overriding default name of "" to something else.

**Comment by herau** [comment]
`xmlMapper.setXMLTextElementName("$");` isn't applicable because this method has a protected scope. But i can handle it with `xmlMapper.getFactory().setXMLTextElementName("$");`

**Comment by cowtowncoder** [comment]
Oh. That may be an oversight... I'll have a look. Don't remember the reason for such access. There is `XmlModule` as well, maybe I thought that'd be the route to take.

**Comment by cowtowncoder** [comment]
Ah yes. Protected access due to `XmlModule` being the intended mechanism, avoiding adding setters in mapper itself. Although if you really want to, can sub-class `XmlMapper`, open up access.
