### ISSUE TITLE
I want a pure xml

### ISSUE THREAD

**Issue by 891877295** [FasterXML/jackson-dataformat-xml#134]
![qq](https://cloud.githubusercontent.com/assets/10719576/5914478/fda48c5a-a630-11e4-86db-5466da877475.png)

@JacksonXmlRootElement(localName="xml")
public class TextMessage{
	// 回复的消息内容
	private String Content;

	public String getContent() {
		return Content;
	}

	public void setContent(String content) {
		Content = content;
	}

}

How can I get the below xml?

![qq 20150127121037](https://cloud.githubusercontent.com/assets/10719576/5913366/b5b3a146-a61d-11e4-8679-1c8e5b4f8f72.png)
OR

**Comment by cowtowncoder** [comment]
You may have misunderstood the role of Github issue tracker. This is not a public question forum, but place for reporting bugs.

For user questions, please use mailing lists.
