### ISSUE TITLE
@JacksonXmlProperty(isAttribute = true) is not working under version 2.5.1

### ISSUE THREAD

**Issue by zhijun** [FasterXML/jackson-dataformat-xml#138]
@JacksonXmlProperty(isAttribute = true) was working under 2.4.5 however not any more with 2.5.1. Seems version 2.5.1 simply ignores this annotation.

**Comment by cowtowncoder** [comment]
No, it should work just fine, no changes were made in this area. Unit tests are passing for the property.

But it is of course possible there could be a bug for a specific case (side-effect of a fix to handling for example). Do you have a simple reproduction of the problem? That would help figure out what is going on.

**Comment by zhijun** [comment]
Actually I work under Scala and after some investigation it's clear that it's jackson-module-scala_2.11 which caused this problem. Thanks and this issue should be closed.

**Comment by cowtowncoder** [comment]
Ok. Thank you for digging through this. I hope the issue with Scala module can be resolved.
