### ISSUE TITLE
Problems with stax-api dependency on Android

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-xml#142]
(note: offshoot of #116)

Although JDK 1.6 does include Stax API (`javax.xml.stream`), Google has chosen to create an arbitrary subset of the same and is not included this API. Earlier it even blocked attempts at including any non-included dependencies in `javax.` namespace, but apparently this has been resolved, at least as far as Stax API is included (by whitelisting?).

But. Since dependency is needed on Android, there is need to either add an otherwise unnecessary dependency (unnecesasry for J2SE/J2EE), which may add unnecessary jar in builds on non-Android platforms; or to add instructions to help Android developers add the dependency explicitly.

I will first add a note on README, for approach two.

**Comment by keshav-iitr** [comment]
@cowtowncoder Do you have any solution for this issue?  I am also facing this issue please help.

**Comment by cowtowncoder** [comment]
@keshav-iitr I don't know anything more; but mailing list (`jackson-user`) has more Android developers; maybe someone knows.

**Comment by cowtowncoder** [comment]
I don't know what else could or should be done here -- the fact remains that `stax-api` appears necessary for Android; but since it is provided by all J2SE platforms current versions of Jackson run (Java 6 and above), it does not make sense to add as a hard dependency.

**Comment by cternes** [comment]
I get the following error while trying to include the Stax API explicitly on Android (v5.0):

> Ill-advised or mistaken usage of a core class (java.* or javax.*) when not building a core library.
> 
> This is often due to inadvertently including a core library file in your application's project, when using an IDE (such as Eclipse). If you are sure you're not intentionally defining a core class, then this is the most likely explanation of what's going on.
> 
> However, you might actually be trying to define a class in a core namespace, the source of which you may have taken, for example, from a non-Android virtual machine project. This will most assuredly not work. At a minimum, it jeopardizes the compatibility of your app with future versions of the platform.
> It is also often of questionable legality.
> 
> If you really intend to build a core library -- which is only appropriate as part of creating a full virtual machine distribution, as opposed to compiling an application -- then use the "--core-library" option to suppress this error message.
> 
> If you go ahead and use "--core-library" but are in fact building an application, then be forewarned that your application will still fail to build or run, at some point. Please be prepared for angry customers who find, for example, that your application ceases to function once they upgrade their operating system. You will be to blame for this problem.
> 
> If you are legitimately using some code that happens to be in a core package, then the easiest safe alternative you have is to repackage that code. That is, move the classes in question into your own package namespace. This means that they will never be in conflict with core system classes. JarJar is a tool that may help you in this endeavor. If you find that you cannot do this, then that is an indication that the path you are on will ultimately lead to pain, suffering, grief, and lamentation.

Has this changed in newer Android versions or what needs to be done in order to get it working?

**Comment by cowtowncoder** [comment]
@cternes I don't know: I don't develop on Android. Please ask on mailing lists.

**Comment by Chubacca** [comment]
@roberttaylor426 FWIW, I managed to get this working on Android by just listing stax as a separate dependency (it looks like javax.* aren't blocked anymore).

`implementation 'javax.xml.stream:stax-api:1.0-2'`

I also had to add this to my proguard:

```
-dontwarn com.fasterxml.**
-keep class com.ctc.wstx.** { *; }
-dontwarn com.ctc.wstx.**
```

This might be helpful to other Android people.
