### ISSUE TITLE
XML RootElement in Lowercase

### ISSUE THREAD

**Issue by ltoinel** [FasterXML/jackson-dataformat-xml#143]
Hi,

We generate POJO using Jsonschema2pojo.
We would like that the XML generated have a lowercase root element name.

For exemple:  
My Java class Person will have a RootElement "Person" into the XML.

Is-it possible to get this feature available ?

Thank-you !

**Comment by cowtowncoder** [comment]
You can use `@JsonRootName` annotation to change the name used. Or, with `ObjectWriter`, method "withRootName(...)" to override whatever name is being used.
