### ISSUE TITLE
Deserialization of an XML with an empty element for a bean valued field forces the field to null, instead of leaving it as initialized by default constructor

### ISSUE THREAD

**Issue by dgaffuri** [FasterXML/jackson-dataformat-xml#146]
Given the class

```
public class TestObject {

    private static class Embedded {

        @JsonProperty private String embeddedId;

        public String toString() {
            return "Embedded[embeddedId=" + embeddedId + "]";
        }
    }

    @JsonProperty private String id;
    @JsonProperty private Embedded embedded = new Embedded();

    public String toString() {
        return "TestObjectWithEmbedded[id=" + id + ", embedded=" + embedded + "]";
    }
}
```

trying to serialize new TestObject() with Include.NON_EMPTY serialization gives

```
<TestObject><embedded/></TestObject>
```

whose deserialization is a TestObject with a null embedded field, instead of an "empty" one.

This is different for JSON (de)serialization, where

```
{"embedded":{}}
```

deserializes correctly, as does XML produced without the NON_EMPTY inclusion:

```
<TestObject><id/><embedded><embeddedId/></embedded></TestObject>
```

[Here's a gist](https://gist.github.com/dgaffuri/f13762df340f0f6c8004) with a test for the four combinations.

**Comment by cowtowncoder** [comment]
Can not reproduce with 2.11 any more; closing.
