### ISSUE TITLE
Complete list of items are not showing up after deserializing XML String into object using Jackson XML mapper

### ISSUE THREAD

**Issue by sparkle8** [FasterXML/jackson-dataformat-xml#151]
http://stackoverflow.com/questions/30174315/complete-list-of-items-are-not-showing-up-after-deserializing-xml-string-into-ob

My input XML string contains a list of entries. When I deserialize it into object using jackson xmlmapper I see only one item is coming. The parent elements have been defined as generic objects in POJO.

**Comment by cowtowncoder** [comment]
As per answer at SO, the problem is that you can not simply use type `Object`, since that does not give enough information to construct meaningful values from XML -- and specifically, there is no way to represent arrays/Lists, just `Map`s.
