### ISSUE TITLE
Please clarify license of Issue97Test.java Copyright Nu Echo Inc.

### ISSUE THREAD

**Issue by apoleon** [FasterXML/jackson-dataformat-xml#153]
Hello,

I am currently in the process of packaging jackson-dataformat-xml for Debian. For

src/test/java/com/fasterxml/jackson/dataformat/xml/failing/Issue97Test.java

the copyright holder is Nu Echo Inc. The name does not appear in any other file and unfortunately they don't give any license information for this test. According to international copyright law this makes the file non-distributable.

Could you please clarify the license of Issue97Test.java?

**Comment by cowtowncoder** [comment]
Looks like Pascal (pgelinas) accidentally had that copyright statement there, and I hadn't noticed it when adding. Removed copyright part, updated author to pgelinas as per contribution.
