### ISSUE TITLE
Type info not serialized when using @JsonAnyGetter 

### ISSUE THREAD

**Issue by Maxouwell** [FasterXML/jackson-dataformat-xml#158]
@JsonAnyGetter state that
>contents of the returned Map are serialized as if they were actual properties of the bean that contains method/field with this annotations

but when the object in the map are annoted with @JsonTypeInfo, the type info is not serialized, although it is on a classic getter.

```Java
public class Test {
	
	public static final ObjectMapper mapper = new ObjectMapper()
			.enable(SerializationFeature.INDENT_OUTPUT);
	
	public static void main(String[] args) throws Exception {
		Index i = new Index(1);
		
		Test1 t1 = new Test1(i, 2);
		Test2 t2 = new Test2(i, 3);
		
		System.out.println(mapper.writeValueAsString(t1));
		System.out.println(mapper.writeValueAsString(t2));
	}

}

@JsonTypeInfo(use=JsonTypeInfo.Id.MINIMAL_CLASS, include=JsonTypeInfo.As.PROPERTY)
public class Index {
	private int x;
	
	public Index(int x) {
		this.x = x;
	}
	
	public int getX() {
		return x;
	}
}

public class Test1 {
	private Index index;
	private int z;
	
	public Test1(Index index, int z) {
		this.index = index;
		this.z = z;
	}
	
	public Index getIndex() {
		return index;
	}
	
	public int getZ() {
		return z;
	}
}

public class Test2 {
	private Index index;
	private int w;
	
	public Test2(Index index, int w) {
		this.index = index;
		this.w = w;
	}
	
	public int getW() {
		return w;
	}
	
	@JsonAnyGetter
	public Map<String, Object> any() {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("index", index);
		return map;
	}
}
```

This output
```
{
  "index" : {
    "@c" : ".Index",
    "x" : 1
  },
  "z" : 2
}
{
  "w" : 3,
  "index" : {
    "x" : 1
  }
}
```
Am I doing something wrong or is this a bug ?

(Jackson 2.5.4)

**Comment by cowtowncoder** [comment]
That does sound like a bug, thank you for reporting it.

I wonder if this would affect json output. I can test that out; my guess is this is XML specific.

**Comment by Maxouwell** [comment]
Well it seems a didn't post this in the right place.
It was mean to be on jackson-databind.

Is ther a way to move it or does I need to recreate it ?

**Comment by cowtowncoder** [comment]
Unfortunately I don't think github has transfer feature for issues. It is my number one wish for new features, since this is quite common.

So, if you could cut-n-paste + recreate, that would be great. Apologies for the hassle.

**Comment by Maxouwell** [comment]
No problem !
New issue is here : https://github.com/FasterXML/jackson-databind/issues/901
