### ISSUE TITLE
handling Maps as specified in http://www.w3.org/2005/07/xml-schema-patterns.html#Map-Unique-Key

### ISSUE THREAD

**Issue by gdelafosse** [FasterXML/jackson-dataformat-xml#160]
Hello
is there a way to configure Jackson mapper to handle Maps as described in this document
http://www.w3.org/2005/07/xml-schema-patterns.html#Map-Unique-Key.
Currently default behaviour is to handle Map this way:
```xml
<HashMap>
  <id1>
    <name>name1</name>
    <type>type1</type>
  </id1>
  <id2>
    <name>name2</name>
    <type>type2</type>
  </id2>
</HashMap>
```
whereas the specification proposes to handle maps this way : 
```xml
<HashMap>
  <item>
    <key>id1</key>
    <value>
      <name>name1</name>
      <type>type1</type>
    </value>
  </item>
  <item>
    <key>id2</key>
    <value>
      <name>name2</name>
      <type>type2</type>
    </value>
  </item>
</HashMap>
```

**Comment by cowtowncoder** [comment]
I don't think there is a way to do that. And I am not sure if that could be supported. Handling of Maps is quite difficult with XML.
