### ISSUE TITLE
POJO @JacksonXmlRootElement

### ISSUE THREAD

**Issue by fabiokiatkowski** [FasterXML/jackson-dataformat-xml#163]
Hi,

I have a class like this:

``@JacksonXmlRootElement(localName="ws_integracao")
public class Cabecalho {``

and I use writeValueAsString(cabecalho)

but the return string sometime does not contains ws_integracao tag.

Someone knows why this happen? What can I do?

**Comment by cowtowncoder** [comment]
@fabiokiatkowski Issue tracker is for reporting specific problems, and not for question or support forum. So you'll have better chance joining Jackson mailing list.

As to your problem, you need to show actual code you use along with expected and actual output. Or perhaps a unit test to show all.

**Comment by fabiokiatkowski** [comment]
@cowtowncoder thanks.
