### ISSUE TITLE
Jackson XML serialization drops elements of Integer type if their value is zero

### ISSUE THREAD

**Issue by rpatrick00** [FasterXML/jackson-dataformat-xml#174]
Carrying on with my little test project to isolate the issues we are seeing with Jackson, I have the following class:
<pre>
@XmlRootElement(name = "employee")
@XmlAccessorType(XmlAccessType.FIELD)
public class Employee {
  @XmlAttribute
  @XmlID
  private String id;

  @XmlElement
  private String name;

  @XmlElement
  private EmployeeType type;

  @XmlElement
  private Integer extension;
  ...
}
</pre>

And the object structure is being put together like this:
<pre>
  public RunThis() {
    Company company = new Company();

    Employee employee1 = new Employee();
    employee1.setId("emp-1");
    employee1.setName("Robert Patrick");
    employee1.setType(EmployeeType.FULLTIME);
    employee1.setExtension(new Integer(32872));
    company.addEmployee(employee1);

    Employee employee2 = new Employee();
    employee2.setId("emp-2");
    employee2.setName("Michael Smith");
    employee2.setType(EmployeeType.CONTRACTOR);
    employee2.setExtension(new Integer(0));
    company.addEmployee(employee2);

    Employee employee3 = new Employee();
    employee3.setId("emp-3");
    employee3.setName("Nick D'Attoma");
    company.addEmployee(employee3);
</pre>

In JAXB, the output is what you would expect:
<pre>
&lt;?xml version="1.0" encoding="UTF-8" standalone="yes"?&gt;
&lt;company&gt;
    &lt;employees&gt;
        &lt;employee id="emp-1"&gt;
            &lt;name&gt;Robert Patrick&lt;/name&gt;
            &lt;type&gt;FULLTIME&lt;/type&gt;
            &lt;extension&gt;32872&lt;/extension&gt;
        &lt;/employee&gt;
        &lt;employee id="emp-2"&gt;
            &lt;name&gt;Michael Smith&lt;/name&gt;
            &lt;type&gt;CONTRACTOR&lt;/type&gt;
            &lt;extension&gt;0&lt;/extension&gt;
        &lt;/employee&gt;
        &lt;employee id="emp-3"&gt;
            &lt;name&gt;Nick D'Attoma&lt;/name&gt;
        &lt;/employee&gt;
    &lt;/employees&gt;
&lt;/company&gt;
</pre>

With Jackson, the &lt;extension&gt; element in missing from the emp-2 employee.  
<pre>
&lt;?xml version='1.1' encoding='UTF-8'?&gt;
&lt;company&gt;
  &lt;employees&gt;
    &lt;employee id="emp-1"&gt;
      &lt;name&gt;Robert Patrick&lt;/name&gt;
      &lt;type&gt;FULLTIME&lt;/type&gt;
      &lt;extension&gt;32872&lt;/extension&gt;
    &lt;/employee&gt;
    &lt;employee id="emp-2"&gt;
      &lt;name&gt;Michael Smith&lt;/name&gt;
      &lt;type&gt;CONTRACTOR&lt;/type&gt;
    &lt;/employee&gt;
    &lt;employee id="emp-3"&gt;
      &lt;name&gt;Nick D'Attoma&lt;/name&gt;
    &lt;/employee&gt;
  &lt;/employees&gt;
&lt;/company&gt;
</pre>

If I set the value to anything non-zero, the element appears.  How can I get Jackson to not remove Integer elements set to 0?

**Comment by rpatrick00** [comment]
Apparently, setting the following Serialization configuration causes this:

<pre>
mapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);
</pre>

But I am not sure why you would want to define a java.lang.Integer(0) as an empty field and turning this off is not an option for us since that makes every empty element show up...

**Comment by cowtowncoder** [comment]
On inclusion criteria, this is

https://github.com/FasterXML/jackson-databind/issues/952

and will be reverted for 2.7. A work-around for 2.6 would be to override serializer for `java.lang.Integer.TYPE`, override `isEmpty()`.

But it sounds like there is a separate bug caused by faulty handling of exclusion in addition to that issue.

**Comment by cowtowncoder** [comment]
Actually, I think this may well be just the "too wide applicability for emptiness check", so I assume it is fixed for 2.7.

**Comment by yuvrajhshinde** [comment]
I am not geeting following header if I use Jackson approach , It is working properly with JAXB.

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
