### ISSUE TITLE
Error Validation DTD on xmlMapper.readValue

### ISSUE THREAD

**Issue by ssdiegosilva** [FasterXML/jackson-dataformat-xml#176]
hello I would like to know how can I make the XmlMapper can look for the DTD file to a different way of abusoluto way.

Or some form of shut validation DTD

```java
try {
            
            JacksonXmlModule module JacksonXmlModule = new ();
            // And configure Then, for example:
            module.setDefaultUseWrapper (false);
            
            ObjectMapper xmlMapper = new XmlMapper (module);
            // Causes not populated objects are not parsed
            xmlMapper.setSerializationInclusion (Include.NON_NULL);

            OpenSrsEnvelope openSrsEnvelope = new OpenSrsEnvelope (openSrsOperation);

            String xml = xmlMapper.writeValueAsString (openSrsEnvelope);

            String response = sendRequest (xml);

            InputStream stream = new ByteArrayInputStream (response.getBytes ());

            xmlMapper.configure (DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
            xmlMapper.configure (DeserializationFeature.WRAP_EXCEPTIONS, false);

            OpenSrsEnvelope responseEnvelope = xmlMapper.readValue (stream, OpenSrsEnvelope.class);

            return responseEnvelope;

        } Catch (Exception e) {
            e.printStackTrace ();
        }
```

It is the following error

java.io.IOException: com.ctc.wstx.exc.WstxParsingException: (was java.io.FileNotFoundException) C: \ Users \ cin_dsilva \ git \ OpenSRS-client \ ops.dtd (The system can not find the specified file)
 at [row, col {unknown-source}]: [2.40]
at com.fasterxml.jackson.dataformat.xml.util.StaxUtil.throwXmlAsIOException (StaxUtil.java:24)
at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser (XmlFactory.java:539)
at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser (XmlFactory.java:29)
at com.fasterxml.jackson.core.JsonFactory.createParser (JsonFactory.java:802)
at com.fasterxml.jackson.databind.ObjectMapper.readValue (ObjectMapper.java:2796)

**Comment by cowtowncoder** [comment]
You may need to configure Stax `XmlInputFactory` to specify root path to use: since you are reading from a basic `InputStream` it does not necessarily have context (current directory) to use. There should be a way to specify alternate `XmlResolver` to use for locating DTD; Woodstox at least supports that.

From error message, however, it looks like XML document uses a hard-coded file path, which is also wrong -- this makes no sense when transferring files over the network.

**Comment by ssdiegosilva** [comment]
Thanks...

I include this code

            XMLInputFactory xmlInputFactory = XMLInputFactory.newInstance();
            
            XMLResolver resolver = new XMLResolver() {
                
                public Object resolveEntity(String publicID, String systemID, String baseURI, String namespace) throws XMLStreamException {
                    
                    /*if ("ops.dtd".equals(systemID)) {
                        return getClass().getResourceAsStream("/opensrs-client/src/main/resources/ops.dtd");    
                    } else {
                        return new ByteArrayInputStream(new byte[0]);                        
                    }*/
                    return new ByteArrayInputStream(new byte[0]);
                }
            };
            xmlInputFactory.setXMLResolver(resolver);

            ObjectMapper xmlMapper = new XmlMapper(xmlInputFactory);

And solve the problem.

**Comment by ssdiegosilva** [comment]
Thanks...

I include this code

XMLInputFactory xmlInputFactory = XMLInputFactory.newInstance();
            
            XMLResolver resolver = new XMLResolver() {
                
                public Object resolveEntity(String publicID, String systemID, String baseURI, String namespace) throws XMLStreamException {
                    
                    if (OPEN_SRS_DTD_SYSTEM_ID.equals(systemID)) {
                        return getClass().getClassLoader().getResource(OPEN_SRS_DTD_SYSTEM_ID);
                    } else {
                        return new ByteArrayInputStream(new byte[0]);                        
                    }
                }
            };
            xmlInputFactory.setXMLResolver(resolver);


And solve the problem.

**Comment by cowtowncoder** [comment]
@ssdiegosilva Excellent! Thank you for sharing this, I assume others may face similar issues.

**Comment by lacyrhoades** [comment]
Where is `xmlInputFactory` in your original example?

**Comment by ssdiegosilva** [comment]
In my original example I not used the XMLInputFactory. In that example I used JacksonXmlModule.

My change was to replace the JacksonXmlModule by XMLInputFactory.

**Comment by ssdiegosilva** [comment]
// JacksonXmlModule module  = new JacksonXmlModule ();
// And configure Then, for example:
// module.setDefaultUseWrapper (false);
//  ObjectMapper xmlMapper = new XmlMapper (module);


final XMLInputFactory xmlInputFactory = XMLInputFactory.newInstance();

            final XMLResolver resolver = new XMLResolver() {

                public Object resolveEntity(final String publicID, final String systemID, final String baseURI, final String namespace)
                        throws XMLStreamException {

                    if (OPEN_SRS_DTD_SYSTEM_ID.equals(systemID)) {
                        return getClass().getClassLoader().getResource(OPEN_SRS_DTD_SYSTEM_ID);
                    } else {
                        return new ByteArrayInputStream(new byte[0]);
                    }
                }
            };
 xmlInputFactory.setXMLResolver(resolver);

 final ObjectMapper xmlMapper = new XmlMapper(xmlInputFactory);

 final String xml = xmlMapper.writeValueAsString(yourObjectHere);
