### ISSUE TITLE
Problem to use the method readTree to parse the xml including collections

### ISSUE THREAD

**Issue by qfxu** [FasterXML/jackson-dataformat-xml#179]
the xml like this:
<code>
&lt;person>
   &lt;name>Tom&lt;/name>
    &lt;address>&lt;zipcode>400-909&lt;/zipcode>&lt;/address>
    &lt;address>&lt;zipcode>300-987&lt;/zipcode>&lt;/address>
&lt;/person>
</code>
I want to use XmlMapper.readTree(String content) to transfer the xml to JsonNode, But the result only include the last zipcode information, what's the problem? while i use this method to parse json, it works ok.

**Comment by cowtowncoder** [comment]
Use of Trees is explicitly not supported, as XML information model differs too much from JSON.

In your case, there is no way to distinguish whether something is an "Object" (distinct key names) or "Array" (sequence of one or more elements). For data-binding this can be resolved from target Java type, but with trees there is no such information.

Tree Model, by default, only works with XML if you use "Object"s and not Arrays.
