### ISSUE TITLE
Globally changing the serialization of a list of items 

### ISSUE THREAD

**Issue by milanov** [FasterXML/jackson-dataformat-xml#186]
I'm using the Jackson XML formatting capabilities together with Spring Boot. In many places the response of the endpoints is paginated using the built-in mechanism from Spring Data (Pageable/Page). However, here comes a problem - the Page object returns it's metadata and in a content field it returns the "chunk" of results:

``` xml
<PageImpl>
   <content>
        <content>
        <id>123</id>
        <title>Title 123</title>
        ...
       </content>
       <content>
       ...
       </content>
   </content>
   <totalElements>3</totalElements>
   <totalPages>1</totalPages>
   <size>20</size>
   ...
</PageImpl>
```

What I'm trying to accomplish is that inside of the content the elements be named with the names of their respective class:

``` xml
<content>
   <article>
      <id>123</id>
      <title>Title 123</title>
      ...
   </article>
   <article>
      ...
   </article>
</content>
```

I've researched and found a way to accomplish that, but it requires annotating the `List<T> content`property (or getter) inside of a class which I cannot modify. Is there a way to globally configure this desired behaviour (perhaps implementing a custom AnnotationResolver)?

**Comment by cowtowncoder** [comment]
The only way that currently allows functionality like this is use of polymorphic types (`@JsonTypeInfo`).
It does not require use of `List` or array as container. But I am not 100% if that would work exactly the way you want, since it would still also include element for property name -- there is no functionality currently to fold these two into just one element.

**Comment by cowtowncoder** [comment]
There is no way to achieve this currently, nor plans: I think I understand what is desired but do not know how this could be achieved internally -- it would require combining list element or object property name and type wrapper.
