### ISSUE TITLE
readTree can't parse an xml with a collection of elements with the same tag

### ISSUE THREAD

**Issue by aterreno** [FasterXML/jackson-dataformat-xml#187]
Hi, 
this seems such a basic functionality that I must have missed something in the configuration of the XmlMapper. 

I am trying to parse something like this: 

```xml
<foo>
	<bars>
		<bar id="one">bar one</bar>
		<bar id="two">bar two</bar>
		<bar id="three">bar three</bar>
		<bar id="four">bar four</bar>
		<bar id="five">bar five</bar>
	</bars>
</foo>
```

It seems like only the last ' bar five' gets parsed, which indicates that an hashmap has been used to collect the tags rather than an array. 

Here's a simple test to reproduce the problem: 

```java
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.assertEquals;


public class JacksonXMLTest {

    private String xml =
            "<foo>\n" +
            "\t<bars>\n" +
            "\t\t<bar id=\"one\">bar one</bar>\n" +
            "\t\t<bar id=\"two\">bar two</bar>\n" +
            "\t\t<bar id=\"three\">bar three</bar>\n" +
            "\t\t<bar id=\"four\">bar four</bar>\n" +
            "\t\t<bar id=\"five\">bar five</bar>\n" +
            "\t</bars>\n" +
            "</foo>";

    @Test
    public void itDoesntWork() throws IOException {
        XmlMapper xmlMapper = new XmlMapper();
        JsonNode jsonNode = xmlMapper.readTree(xml);

        assertEquals(5, jsonNode.findValues("bar").size());
    }
}
```

built with 

```gradle
compile('com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.6.3')
````

Is there something specific to setup in the JacksonXmlModule to get it working?
Or this sort of XML format is just not supported? 

Thanks in advance

**Comment by cowtowncoder** [comment]
As per `README` of this project, tree model (`JsonNode`) can not fully represent all kinds of XML documents, and officially tree model is not supported at all for this module.
It is possible to use `JsonNode` for some use cases, but this specific usage will not work and is unlikely to ever be supported: problem being that XML has no native structures to distinguish between "Objects" and "Arrays", and as a result only "Objects" are recognized. This means that repeated tags will effectively be collated into a single value.

**Comment by bharathloka** [comment]
Even I'am having the same issue how did you do it @aterreno

**Comment by cawena** [comment]
JSONObject xmlJsonObj = XML.toJSONObject(YourXMLString);
                    String jsonPrettyPrintString = xmlJsonObj.toString(PRETTY_PRINT_INDENT_FACTOR);
                    JsonNode jsonNodeNew = mapper.readTree(jsonPrettyPrintString);

**Comment by DavidRG13** [comment]
Hi @cawena, @cowtowncoder, @aterreno ,

did you manage to fix it it or did you find a workaround?

`String xmlStr = "<bla><statusFlags>\n" +
                "                <statusFlagName>PWORD</statusFlagName>\n" +
                "                <statusFlagName>NO_DEPLIM</statusFlagName>\n" +
                "            </statusFlags></bla>";
        Bla resultObj = JacksonUtils.mapper.readValue(xmlStr, Bla.class);

        Assert.assertEquals(2, resultObj.someArray.size());`


That works perfectly, but if I read the same element inside a CustomDeserializer, I get only 1 element

**Comment by vikramp** [comment]
It would have been nice to provide a fix or a solution to this problem.

**Comment by cowtowncoder** [comment]
As per discussion, as of now use of Tree Model is simply not supported with XML module; some parts may works, others (like duplicated elements) not so much.

Having said that I don't see why access via `JsonParser` would not work: duplicates will not for with POJOs for obvious reasons, but they can be handled to work with `Collection` types. So custom deserializer should see them. If not, that would be a bug. But if so, would need to have reproduction (unit test); and filed as a new issue, since it's about streaming API, not tree model.

**Comment by p0sitron** [comment]
For future googlers: 
Since we know the structure of this specific list you can do something like:
```java
List<List<JsonNode>> bars = xmlMapper.readValue(xml, new TypeReference<List<List<JsonNode>>>() { });
assertEquals(5, bars.get(0).size());
```
Not that it looks very pretty.

**Comment by darioseidl** [comment]
This workaround works well for me: https://stackoverflow.com/a/53296833/401712

**Comment by cowtowncoder** [comment]
Note: Jackson version 2.12 DOES allow reading of duplicate elements with `readTree()`.
(also works for nominal type of `java.lang.Object`, so-called "untyped" binding).
