### ISSUE TITLE
jackson-dataformat-xml:Unrecognized field “_type”,but there is no property named “ _type” in my class

### ISSUE THREAD

**Issue by goahead77** [FasterXML/jackson-dataformat-xml#200]
Hi~,when i use jackson-dataformat-xml deserialize xml ,I have some trouble and here is my case:http://stackoverflow.com/questions/38025648/jackson-dataformat-xmlunrecognized-field-type-but-there-is-no-property-named

**Comment by cowtowncoder** [comment]
I think I would need a simpler unit test to verify what the problem is. I can not see anything wrong about code itself, so it seems it should work. Just make sure to use a recent version of XML mapper: ideally 2.7.5, since there have been fixes even quite recently.

**Comment by goahead77** [comment]
I has solved by adding a annotation @JsonIgnoreProperties(ignoreUnknown = true) on my impl class
