### ISSUE TITLE
POJO for Node with mixed items

### ISSUE THREAD

**Issue by phystem** [FasterXML/jackson-dataformat-xml#201]
```
<Root ref="abc">
    <Page ref="p1">
        <Object ref="o1"></Object>
        <ObjectGroup ref="o2">
            <Object ref="o1"></Object>
            <Object ref="o2"></Object>
        </ObjectGroup>
        <Object ref="o3"></Object>
        <Object ref="o4"></Object>
    </Page>
</Root>
```

I want to wite a POJO for the above xml. Asked a question is [StackOverFlow](http://stackoverflow.com/questions/38075633/jackson-xml-pojo-deserialization-using-xmlmapper)

The root will have n **Page** and **Page** will have n **Object** as well as n **ObjectGroup** and **ObjectGroup** will have n **Object**. where **n >= 0**

I looked into Polymorphic de serialization as well. But How to handle this situation

**Comment by cowtowncoder** [comment]
@phystem Usage questions should be sent to https://groups.google.com/forum/#!search/jackson-users unless there is an actual issue to be resolved.
