### ISSUE TITLE
ToXmlGenerator.java WRITE_BIGDECIMAL_AS_PLAIN is used the wrong way round

### ISSUE THREAD

**Issue by xmluzr** [FasterXML/jackson-dataformat-xml#210]
In `jackson-dataformat-xml/src/main/java/com/fasterxml/jackson/dataformat/xml/ser/ToXmlGenerator.java`

Line 970 and 972 should be swapped

https://github.com/FasterXML/jackson-dataformat-xml/blob/3673c0645333dccf06933cbda4810197872cb7a6/src/main/java/com/fasterxml/jackson/dataformat/xml/ser/ToXmlGenerator.java#L970

**Comment by cowtowncoder** [comment]
True. Will need to see if this also affects 2.7.

**Comment by cowtowncoder** [comment]
Fixed in 2.7.8 as well as 2.8.3.
