### ISSUE TITLE
XmlMapper.readValue(File, Class) don't close a File on error

### ISSUE THREAD

**Issue by marcieldeg** [FasterXML/jackson-dataformat-xml#212]
The method XmlMapper.readValue(File, Class) don't close the file if it has erros (for example, if File isn't XML).

`XmlMapper mapper = new XmlMapper();
try {
  File f = new File("not-xml.txt");
  mapper.readValue(f, Object.class);
} catch (Exception e) {
  f.delete(); //error
}`

version 2.6.3

**Comment by cowtowncoder** [comment]
Just to make sure: you are saying that the underlying `FileOutputStream` is not closed? (since files are not closed in Java, streams are).

If so, this would probably be bug for all mappers, including json one.

**Comment by cowtowncoder** [comment]
@marcieldeg Ok. And if there is a more general problem, go ahead and file issue against `jackson-databind`. Thank you for verifying!
