### ISSUE TITLE
Default order will not be respect if custom XML tag is set

### ISSUE THREAD

**Issue by simonwg** [FasterXML/jackson-dataformat-xml#215]
If I don't explicitly set the @JsonPropertyOrder in class, the output of XML should follows the default ordering of the property in source code. However, I found that if @JacksonXmlProperty is being set on particular property, such property will be put at the end of the xml tag list.

e.g.
```
public class Wrapper {

        private String a;
        private String d;
        @JacksonXmlProperty(localName = "CCCC")
        private String c;
        private String b;
        private String e;
}
```

This will output `<Wrapper><a/><d/><b/><e/><CCCC/></Wrapper>`. The custom `<CCCC/>` tag will be put at the end.

If @JacksonXmlProperty annotation is removed, it will output `<Wrapper><a/><d/><c/><b/><e/></Wrapper>`

I think this issue is different from https://github.com/FasterXML/jackson-dataformat-xml/issues/50 as it is rely on default order

**Comment by cowtowncoder** [comment]
@simonwg Unfortunately JDK does not guarantee any ordering of fields, methods exposed via reflection, so Jackson likewise does not (and can not) guarantee such ordering constraints.
To be ensure of specific ordering, `@JsonPropertyOrder` must be defined (or, `MapperFeature.SORT_PROPERTIES_ALPHABETICALLY`).

With that caveat it seems unnecessary that name override should change whatever default ordering would be, based on (potentially arbitrary) order that Fields/Methods are exposed by Reflection.
So I hope to have a look at whether this could be improved or not.

**Comment by simonwg** [comment]
I understand that this is the limitation for reflection. If would be nice if certain caveat could be added jackson-dataformat-xml gh page, as I think XML users should care more on XML tag ordering than JSON ones. It might not be that intuitive if the default ordering is non-deterministic.

**Comment by cowtowncoder** [comment]
@simonwg There may be something within XML module handling that adds additional (and unnecessary from user perspective) shuffling. If so I'll try to remove that.
