### ISSUE TITLE
xmlns in root xml tag doesn't get parsed

### ISSUE THREAD

**Issue by dcassfid** [FasterXML/jackson-dataformat-xml#227]
It seems that an attribute with name xmlns in the root of an xml document will not be parsed.  For example:

pom.xml

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.test</groupId>
  <artifactId>test</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>test</name>
  <description>test</description>
  <dependencies>
  	<dependency>
  		<groupId>com.fasterxml.jackson.core</groupId>
  		<artifactId>jackson-databind</artifactId>
 		<version>2.8.7</version>
  	</dependency>
	<dependency>
		<groupId>com.fasterxml.jackson.dataformat</groupId>
		<artifactId>jackson-dataformat-xml</artifactId>
  		<version>2.8.7</version>
	</dependency>
	<dependency>
		<groupId>com.fasterxml.woodstox</groupId>
		<artifactId>woodstox-core</artifactId>
		<version>5.0.3</version>
	</dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
    </dependency>
  </dependencies>
</project>
```
Bean
```
@JacksonXmlRootElement(localName="Metadata")
public class DocumentMetadata {

	@JacksonXmlProperty(isAttribute=true)
	private String xmlns;
	@JacksonXmlProperty(localName="authorization")
	private String authorization;
	public String getXmlns() {
		return xmlns;
	}
	public void setXmlns(String xmlns) {
		this.xmlns = xmlns;
	}
	public String getAuthorization() {
		return authorization;
	}
	public void setAuthorization(String authorization) {
		this.authorization = authorization;
	}
	@Override
	public String toString() {
		return "\nDocumentMetadata\n[xmlns=" + xmlns + ",\nauthorization=" + authorization + "]";
	}
}
```
XML:
```
    <Metadata` xmlns="uuid:fafb7e69-a6e0-48c4-b29b-690d42742a21">
       <authorization>Yes</authorization>
    </Metadata>
```
JUnit test:
```
	@Test
	public void test() {
		
		String test="<Metadata xmlns=\"uuid:fafb7e69-a6e0-48c4-b29b-690d42742a21\"><authorization>Yes</authorization></Metadata>";
		ObjectMapper xmlMapper = new XmlMapper();
		try {
			DocumentMetadata dm = xmlMapper.readValue(test,DocumentMetadata.class);
			System.out.println("XMLNS: "+dm.getXmlns());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
```
results in the output of:
XMLNS: null

Simply change xmlns in the xml to xmlns2 (and update the code accordingly), and it will work, showing the output of the JUnit to be:
XMLNS2: uuid:fafb7e69-a6e0-48c4-b29b-690d42742a21

Obviously this is a simplified example.  The real xml that I am dealing with comes from a 3rd party product that my company has purchased, and so I have to deal with the xml it produces.  Everything is fine with the exception of the xmlns attribute, which this product produces and requires, and I can't change it.

I have tried putting the JacksonXmlProperty annotation on the property, the getter, and the setter.  I've tried it with a localName and without, with namespace and without, and I've tried it with woodstox and without.  Am I missing something here, or is this really a bug?

**Comment by cowtowncoder** [comment]
@dcassfid You may be bit mistaken here: `xmlns` namespace is virtual in the sense that they define namespace bindings (either for named namespace prefix, or the "default namespace"), but are not part of actual data. This means that they are not exposed as actual attributes at all; and as such can not be bound through databinding.

So: as far as xml module can see, there is no `xmlns` attribute, just namespace bindings (or rather, effects of those that apply to elements and attributes).

**Comment by cowtowncoder** [comment]
And just to make sure above makes sense: namespace pseudo-attribute handling is done by XML parser (woodstox, aalto, xerces), so below level of Jackson.

However! If you do NOT want namespace handling, many parsers expose a way to configure them so that no namespace-handling occurs at all. If so, `xmlns` (etc) are exposed as regular attributes: and possible namespace prefixes are left as is, instead of being split into local name/namespace pairs.
For Woodstox and Aalto this is by configuring `XmlInputFactory` (using `setProperty()`... I think), and then constructing `XmlMapper` by explicitly passing properly configured input factory.

**Comment by dcassfid** [comment]
Got it.

```
XMLInputFactory inputFactory = XMLInputFactory.newFactory();
inputFactory.setProperty("javax.xml.stream.isNamespaceAware", false);
XmlMapper xmlMapper = new XmlMapper(inputFactory);
```
The above fixes the issue.

Thanks!
