### ISSUE TITLE
Error:trouble processing "javax/xml/bind/Binder.class"

### ISSUE THREAD

**Issue by boomsya** [FasterXML/jackson-dataformat-xml#238]
android studio 2.3.2
dependencies for this lib:
compile group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-xml', version: '2.9.0.pr3'
compile group: 'javax.xml.bind', name: 'jaxb-api', version: '2.2.12'

Error:Execution failed for task ':app:transformClassesWithDexForDevDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex 'C:\Users\kolio\.gradle\caches\modules-2\files-2.1\javax.xml.bind\jaxb-api\2.2.12\4c83805595b15acf41d71d49e3add7c0e85baaed\jaxb-api-2.2.12.jar' to 'Z:\build\intermediates\transforms\dex\dev\debug\folders\1000\10\jaxb-api-2.2.12_3e8723a2ab4f6ea021e7276f169b0687fdc79ad6'

**Comment by cowtowncoder** [comment]
This sounds like Android build problem, so I can't help much.
You may want to ask on mailing lists if other Android developers might know what gives.

Since gradle is involved perhaps you can also clear modules it has cached; at least Maven sometimes manages to get into state where cached artifacts are corrupt locally. So perhaps something similar could occur with gradle.

**Comment by fan90910** [comment]
i met the same question, i found the reason is android studio project's target jdk version is jdk1.7, but there are some files conflicted with files in stax-api-1.0-2.jar, such as file 'javax/xml/stream/EventFilter.class'. So, anyone has some advices?

**Comment by fan90910** [comment]
@boomsya @cowtowncoder

**Comment by cowtowncoder** [comment]
@fan90910 those classes form Stax API which is include in JDK 6 and above, but formerly were excluded from Android. If they are now part of SDK now just exclude `stax-api-1.0-2.jar` and rely on SDK provided ones. They are just API types (interfaces, abstract classes), not implementations.
