### ISSUE TITLE
Remove indirect dependency to JAXB

### ISSUE THREAD

**Issue by markusjw** [FasterXML/jackson-dataformat-xml#239]
Hello,
do you see any chance to remove the dependency from jackson-dataformat-xml to jackson-module-jaxb-annotations? This is an optional module, so it would be nice if the coupling could be more loose.

The problem for me is that I would like to use jackson-dataformat-xml with Java 8 compact3 profile which does not contain JAXB.

**Comment by cowtowncoder** [comment]
Unfortunately this is something I couldn't figure out how to do (without resorting to brittle access via reflection); it was more a question whether to make XML format module depend on JAXB or vice versa.Both approaches are sub-optimal.
 I did spend some time trying to think of a way untangling it, a while ago, but while some of dependencies were reduced (that is, there's refactoring for annotation introspector usage), couldn't get things fully dynamic.

I would be open to ideas of how to remove this dependency, esp. for Jackson 3.x (which is what we'll be working towards after 2.9 is released).

On `compact3` profile: does that contain `javax.xml.stream` package? This is also required by xml format module, and is hard dependency. I am mostly asking to know if there might be other blockers for your use.

**Comment by markusjw** [comment]
`java.xml.stream` is part of JAXP and this is contained in compact2 (crypto is added in compact3):
http://www.oracle.com/technetwork/java/embedded/resources/tech/compact-profiles-overview-2157132.html

**Comment by cowtowncoder** [comment]
@markusjw Ok thank you for clarifying that. I asked because it has been missing on many partial-JDK environments (like GAE, Android).

**Comment by cowtowncoder** [comment]
I don't think this is doable; closing.
