### ISSUE TITLE
Spring-boot jackson error on Maven with war file, but not jar file with com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z on Ubuntu 16.0.4

### ISSUE THREAD

**Issue by bangph** [FasterXML/jackson-dataformat-xml#240]
I have a very weird problem with Spring-boot 1.5.2 build with Maven to war package which it has error with Jackson dependency, only on Ubuntu 16.04 as I'm using another Centos 7 and no problem with starting application as war or jar file.

After building with Maven to jar or war, I can run built package with

javar -jar target/project.war (or project.jar) 
and Embedded Tomcat will start. Also the war package could be deployed to an external Tomcat in webapps directory of Centos 7. For Ubuntu 16.04, I could only run .jar file with Tomcat embedded but not war file with Tomcat Embedded/External.

``Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.filter.OrderedHttpPutFormContentFilter]: Factory method 'httpPutFormContentFilter' threw exception; nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
    ... 26 more
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
    at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:564)
    at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:474)
    at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.build(Jackson2ObjectMapperBuilder.java:588)
    at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.<init>(MappingJackson2HttpMessageConverter.java:57)
    at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:61)
    at org.springframework.web.filter.HttpPutFormContentFilter.<init>(HttpPutFormContentFilter.java:63)
    at org.springframework.boot.web.filter.OrderedHttpPutFormContentFilter.<init>(OrderedHttpPutFormContentFilter.java:29)
    at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration.httpPutFormContentFilter(WebMvcAutoConfiguration.java:142)``
`
Here is the pom file https://pastebin.com/13MwTm89 which I only add another dependency from Jackson for deserializing XML to object.

 <dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.8.7</version>
</dependency>
here is the full dependencies for Jackson

mvn dependency:tree | grep 'jackson' 
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.8.7:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.8.7:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.7:compile
[INFO] |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.8.7:compile
```
I could not find answers from Spring boot github as the author (Andy Wilkinson) closed the issue immediately so I have to post here (copied from: https://stackoverflow.com/questions/44367329/spring-boot-jackson-error-on-maven-with-war-file-but-not-jar-file-with-com-fast). 

Does anybody have an idea about this problem? Thanks.

**Comment by cowtowncoder** [comment]
That definitely sounds like version compatibility problem: you have an old(er) version of one of components (most likely `jackson-core`) in your classpath. One reason why this might only occur on specific platform is that classloaders tend to choose one of conflicting jars arbitrarily (that is, ordering is not defined or stable; possibly based on order that underlying file system exposes them?).

Fundamentally `JsonFactory` class that is loaded is from an older version, and something compiled against newer one (2.8) will trigger a linker failure.

I wish I could help you more, but I hope this helps get you looking into right path. Maven should usually prevent inclusion of multiple jars, but perhaps this somehow fails.
Versions you indicate all look right. and you are including things that are needed.

One thing that might help would be to use `jackson-bom`, version 2.8.7, to specify required versions.
This is usually used either via parent pom, or "import"ed -- it's a pom-only artifact, there is no jar.
But it should more reliably specify consistent set of jars to included.

**Comment by bangph** [comment]
Many thanks for your quick reply and detail answer, appreciated. I will post the problem here so if anyone has same can find solution (maybe not in general).

I finally found the problem after trying to comment out each dependency individually in pom.xml, it is due to a fasterxml from very old version in an internally project which is generated to jar file and I included in pom.xml of main project.

The internal project contains some dependencies and I think one of them contains this old jackson-core library, I think it is grpc or protobuf.

   

    <dependencies>
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-all</artifactId>
                <version>0.12.0</version>
            </dependency>
            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-java</artifactId>
                <version>3.0.0-beta-1</version>
            </dependency>
    
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>4.12</version>
            </dependency>
        </dependencies>


Somehow in Ubuntu 16.04, Maven 3.3.9 prefer this jackson-core instead of newest version from Spring boot or specified directly in pom.xml.

It does not happen when in Centos 7 with Maven 3.5.0 when it runs without problem with Jackson as it used the newest dependency.

**Comment by cowtowncoder** [comment]
@bangph Thank you for the update! It definitely sounds mysterious, as direct dependency should have precedence over transitive dependency. About the only thing I can think of is that another jar could simply include classes from `jackson-core` (perhaps `protobuf-java`?), in which case classes from different jars could conflict in unexpected ways.
