### ISSUE TITLE
Deserialization does not trim

### ISSUE THREAD

**Issue by alvico** [FasterXML/jackson-dataformat-xml#241]
We are trying to deserialize an xml where some times an element comes empty but with a line break in the value:

Example1:

```xml
<node>
 <element>
  <title>sometext</title>
 </element>
 <element>
  <title>sometext</title>
 </element>
...
</node>
```

Example2:

```xml
<node>
</node>
```

*added the "" to visualize the end node 
Example 2 throws the following error:
no String-argument constructor/factory method to deserialize from String value ('
')

We do have set the following mapper configurations:
    mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
    mapper.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true)
    mapper.configure(DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT, false)
    mapper.configure(DeserializationFeature.FAIL_ON_INVALID_SUBTYPE, false)
    mapper.configure(DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT, true)
    mapper.configure(DeserializationFeature.FAIL_ON_NULL_CREATOR_PROPERTIES, false)

also in the pojo:
@JsonInclude(JsonInclude.Include.NON_NULL) @JacksonXmlProperty(localName="node") val affectations: List<Element>? for the attribute in the node pojo
@JsonInclude(JsonInclude.Include.NON_NULL) for the element pojo

**Comment by cowtowncoder** [comment]
I would need a reproduction; textual description can be helpful but is not sufficient to know what is going on and whether behavior is expected. Especially definition of Java class to bind data to is absolutely required, as that defines expected XML structure to match it.

**Comment by alvico** [comment]
I've updated the description since the examples where not visualized correctly since some characters where not escaped properly. 

We are working with kotlin but not using anything particular from it for this task.

The class for the elements re the following:
data class Node(
         @JsonInclude(JsonInclude.Include.NON_NULL)
        @JacksonXmlProperty(localName="element") val affectations: List<Element>?)

@JsonInclude(JsonInclude.Include.NON_NULL)
data class Element(
        @JacksonXmlProperty(localName="title") val title: String? = "")

the xml is the one avobe

**Comment by cowtowncoder** [comment]
This is not a reproduction (... and not in Java). I can not help without reproduction.

**Comment by alvico** [comment]
It's in kotlin true, but the reproduction is quite straight forward. I'm not sure if I made my self clear, we the framework encounters a node without text inside but with "\n" (new line) it fails with the reported error. Python handles this quite straight forward, I'm not sure, an quite frustrated, about why java (kotlin) are struggling to parse XMLs

**Comment by cowtowncoder** [comment]
Can not reproduce without unit test. May be reopened with a test fail.

**Comment by alvico** [comment]
I do not agree with this, I think it was clearly explained and easy to reproduce

**Comment by cowtowncoder** [comment]
@alvico that made no sense, no test failure, nothing -- you are just wasting my time here.
