### ISSUE TITLE
Add new feature, `FromXmlParser.Feature.EMPTY_ELEMENT_AS_NULL`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-xml#246]
Since there are two possible ways to expose XML empty element (like "<tag/>" -- but not "<tag></end>"), it seems reasonable to allow configuration of how this is to be exposed.
Due to backwards compatibility reasons, setting should default to `true`, so that by default empty element would be exposed as equivalent of JSON `null` token (`JsonToken.VALUE_NULL`).
But disabling of this feature would instead expose it as `JsonToken.VALUE_STRING` with text value of "" (empty String).

**Comment by anton-johansson** [comment]
I'm really looking forward to this feature. Is there any ETA on 2.9.0?

I see a bunch of pre-releases here:
http://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-xml

But none of them seem to include this commit.

**Comment by cowtowncoder** [comment]
I have been hoping to finalize 2.9.0 for a while now; 2.9.0.pr4 is meant as the last pre-release version.
I am now hoping to get 2.9.0 out by end of July 2017.

**Comment by anton-johansson** [comment]
Cool, thanks for the update!
