### ISSUE TITLE
Map with nested lists to XML ignoring provided names

### ISSUE THREAD

**Issue by magrossi** [FasterXML/jackson-dataformat-xml#249]
Hi,

When serializing a Map<String,Object> to XML I get a strange result (same object to JSON works perfectly).

Objects:
```java
@XmlRootElement(name = "object")
public class MyObject {
  Map<String, Object> content;
}
@XmlRootElement(name = "item")
public class MyOtherObject {
  // bunch of properties
}
```

Now if I do:
```java
// MyObject obj =...
// List<MyOtherObject> mylist =...
obj.content.put("items",mylist);
```

I would expect the XML to look like:
```xml
<object>
   <content>
       <items>
           <item>
                  item stuff
           </item>
           <item>
                  another item stuff
           </item>
       </items>
   </content>
</object>
```

But in reality it looks like:
```xml
<object>
   <content>
       <items>
            item stuff
       </items>
       <items>
             another item stuff
       </items>
   </content>
</object>
```

It is ignoring the `XmlRootElement` name I've provided and it's just repeating the map key name for each element on the list.

**Comment by cowtowncoder** [comment]
This is working as designed: `@XmlRootElement` only works for the root value (outermost object being serialized/deserialized). There is no annotation to wrap property values currently.
