### ISSUE TITLE
JacksonXmlModule _must_ be passed via constructor

### ISSUE THREAD

**Issue by nkiesel** [FasterXML/jackson-dataformat-xml#258]
I needed to disable the wrapper and thus used
```kotlin
val xmlModule = JacksonXmlModule().apply { setDefaultUseWrapper(false) }
val xmlMapper = XmlMapper().apply { registerModules(xmlModule, KotlinModule()) }
```

While this worked it ignored the `useWrapper=false` setting.  I instead have to use
```kotlin
val xmlModule = JacksonXmlModule().apply { setDefaultUseWrapper(false) }
val xmlMapper = XmlMapper(xmlModule).apply { registerModules(KotlinModule()) }
```

This "special" treatment of the module passed in the constructor was unexpected and I could not find anything about that in the documentation either.

Note 1: This is Kotlin code, but I'm sure the behavior will be identical for Java
Note 2: I know it's too late but I still have to find someone who wants `useWrapper=true`

**Comment by cowtowncoder** [comment]
I would need a Java reproduction here, with a new version: setting should work and if not that is a bug. But I unfortunately can not add a Kotlin dependency from XML module, even for tests.

Will close for now but may be reopened with reproduction.

**Comment by nkiesel** [comment]
This is still happening even with 2.11.0:
```kotlin
data class Person(val name: String, val age: Int)
data class Team(val members: List<Person>)
fun y1() {
    val xmlModule = JacksonXmlModule().apply { setDefaultUseWrapper(false) }
    val xmlMapper1 = XmlMapper(xmlModule).apply { registerModules(KotlinModule()) }
    val xmlMapper2 = XmlMapper().apply { registerModules(xmlModule, KotlinModule()) }
    val t = Team(listOf(Person("Joe", 15)))
    println(xmlMapper1.writeValueAsString(t))
    println(xmlMapper2.writeValueAsString(t))
}
```
prints
```
<Team><members><name>Joe</name><age>15</age></members></Team>
<Team><members><members><name>Joe</name><age>15</age></members></members></Team>

```

**Comment by nkiesel** [comment]
I can push the code to reproduce that to a github repo or attach here if you want.

**Comment by cowtowncoder** [comment]
@nkiesel Adding here would be fine

**Comment by nkiesel** [comment]
[jackson-kotlin.zip](https://github.com/FasterXML/jackson-dataformat-xml/files/4670810/jackson-kotlin.zip)
run using `./gradlew run`

**Comment by cowtowncoder** [comment]
@nkiesel Thank you, but as I noted earlier what I really is Java-only replication. I do believe it happens with Kotlin module but I can not really use reproduction that relies on kotlin module -- that can only be done within Kotlin module repo.

But I'll see if I can just create similar setup with Java (but without Kotlin module). If that fails, I will transfer this issue to `jackson-module-kotlin` and see if its maintainers have any idea.

**Comment by cowtowncoder** [comment]
Ok. Looking at this situation, I think that this has to be addressed through documentation and possibly some changes to API. But basically you should not try to explicitly register `JacksonXmlModule` -- it is more internal implementation detail than anything else (and removed from 3.0 since it's awkward mechanism to use).

But you do not need to use `JacksonXmlModule` to change default wrapper state; there are 2 mechanisms as of 2.10:

1. Newer Builder-based approach
2. Direct change to `XmlMapper` (since 2.7; deprecated in 2.10 but will remain in 2.x, only removed from 3.0)

```java
XmlMapper mapper = XmlMapper.builder()
   .defaultUseWrapper(false)
   .build();
// OR
XmlMapper.setDefaultUseWrapper(false);
```

I hope this helps.

**Comment by nkiesel** [comment]
so in summary, the currently "best" way is to use
```java
val xmlMapper = XmlMapper.builder().defaultUseWrapper(false).build().registerKotlinModule()
```

**Comment by nkiesel** [comment]
Thanks for updating the documentation. Feel free to close this  again.

**Comment by cowtowncoder** [comment]
@nkiesel yes, that's the recommended way. Builder style will be the only mechanism in 3.0, allowing fully immutable implementation; in 2.x it is added for to ease (eventual) migration and make it easier to configure format-specific mappers.
