### ISSUE TITLE
Is it possible to ignore non-array element in array?

### ISSUE THREAD

**Issue by Sonique** [FasterXML/jackson-dataformat-xml#261]
Is it possible to ignore element in xml array when parsing with jackson?
for example
```
<array-wrapper>
     <element>foo</element>
     <element>bar</element>
     ...
     <has-more>true</has-more>
</array-wrapper>
```
I think it's not goot idea to put in wrapper another kind of elements, by I work with external source and can't change model. Now Jackson couldn't parse array when another element included.

**Comment by cowtowncoder** [comment]
No, this is not possible.
