### ISSUE TITLE
JacksonXmlProperty annotation not work in Kotlin Data class

### ISSUE THREAD

**Issue by Sonique** [FasterXML/jackson-dataformat-xml#263]
Problem with Kotlin data classes. 

Example:
in this case annotations *doesn't works*
```
data class Request(val verno: String = VERSION, val doc: Doc,
                           @JacksonXmlProperty(isAttribute = true) val command: String = COMMAND)
```

And in this *will work*:
```
data class Request(val verno: String = VERSION, val doc: Doc) {
    @JacksonXmlProperty(isAttribute = true) val command: String = COMMAND
}
```

Version 2.9.0

**Comment by alexashley** [comment]
Ran into this also. Using [`jackson-module-kotlin`](https://github.com/FasterXML/jackson-module-kotlin) fixed it.

**Comment by jeeftor** [comment]
Ran into the same issue - the `jackson-module-kotlin` didnt fix anything for me

**Comment by cowtowncoder** [comment]
Either need a Java-only reproduction (if equivalent could be created), or, filed under `jackson-module-kotlin` (I can transfer if necessary). But it could be as per @alexashley's comment that maybe original case did not use Kotlin module -- if so, fix is to use it.

Will close, may be reopened either with Java-based reproduction, or, if still reproducible with Jackson 2.11.0, I can re-open and transfer.
