### ISSUE TITLE
Jackson not parsing Timestamp correctly

### ISSUE THREAD

**Issue by cheseaux** [FasterXML/jackson-dataformat-xml#264]
I'm having trouble parsing `java.sql.Timestamp` from XML files using Jackson 2.8.5. Somehow the milliseconds are padded with zeros on the left side.

Here is a minimal example showing that :

    public class Foo {

        @JacksonXmlProperty(localName = "ts")
        Timestamp ts;

        public static void main(String[] args) throws IOException {
            String xml = "<Foo><ts>2017-09-21T11:25:32.1Z</ts></Foo>"
            Foo foo = new XmlMapper().readValue(xml, Foo.class);
            System.out.println("foo.ts = " + foo.ts);
        }
    }

> foo.ts = 2017-09-21 11:25:32.**00**1

Whereas if I parse the string manually, I get the expected value

`System.out.println(Instant.parse("2017-09-21T11:25:32.1Z"));`

> 2017-09-21 11:25:32.1

**Comment by cowtowncoder** [comment]
Ok. The very first thing to do is to try this with latest patch, `2.8.10`.

If that still exhibits the issue (there are some fixes wrt `StdDateFormat` handling in that or `2.8.9`), problem is likely to be with main `jackson-databind` since XML module does not deal with higher level data-binding.

**Comment by cheseaux** [comment]
I just tried with `2.8.10` but same behavior

**Comment by cowtowncoder** [comment]
This does not really look XML specific, so would move to `jackson-databind`, but I can not actually reproduce the problem any more with 2.11: output is as expected at this point.
