### ISSUE TITLE
parse object to xml,but get the result like "&lt;gpsx&gt;0.0&lt;/gpsx&gt;&lt;gpsy&gt;0.0&lt;/gpsy&gt;"

### ISSUE THREAD

**Issue by eshxcmhk** [FasterXML/jackson-dataformat-xml#267]
version:
jdk:1.6
Jackson:2.7.9

serialize code:

```java
            JacksonXmlModule module = new JacksonXmlModule();
            module.setDefaultUseWrapper(true);
            XmlMapper mapper = new XmlMapper(module);
            mapper.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            mapper.writeValue(outputStream, obj);
//            return mapper.writeValueAsString(obj);
            return outputStream.toString();
```

the class of obj:

```java
public class Gps{
            public float gpsx;
            public float gpsy;
}
```

Expected result:
    <gpsx\>0.0\</gpsx\>\<gpsy\>0.0\</gpsy\>

What should i do?
Thanks for help!

**Comment by cowtowncoder** [comment]
This is not enough to reproduce the problem, or even quite explain what the problem is: I have no idea what type of `obj` is.

**Comment by eshxcmhk** [comment]
the comment is updated

**Comment by eshxcmhk** [comment]
@cowtowncoder the comment is updated

**Comment by cowtowncoder** [comment]
Ok, first of all, I assume you'd mean

     <Gps><gpsx>0.0</gpsx><gpsy>0.0</gpsy></Gps>

since XML requires a single root.

But code as is should serialize it like that. It would not double-encode output.
Maybe you are returning this value to something that then further XML serializes it?
This would happen if you are using framework like Spring Boot.

Also: please use mailing list for (further) questions -- issue tracker is for reporting issues:

https://groups.google.com/group/jackson-user/

**Comment by eshxcmhk** [comment]
@cowtowncoder But I use this in the java server, and deserialize it in the project of Android or IOS.

**Comment by cowtowncoder** [comment]
Just print out what `return outputStream.toString();` gives you and that should not have escaping but xml content as you would expect. The only explanation for output you include would be if that result String was further passed to XML generator.

**Comment by eshxcmhk** [comment]
@cowtowncoder It's my fault. I didn't think about this. But the really problem which caused is,
I defined a global class for the java interface like:
``` java
class RPCResult{
public int result;
public String message;
public String data;
}
```
the 'data' is the xml of obj like Gps, so when I serialize the RPCResult, and print the result string, the content of data is incorrect

**Comment by cowtowncoder** [comment]
@eshxcmhk Yes, that makes sense. If contents are already XML, then serialization would simply encode them as XML character data with escaping.

For what it is worth, you can embed such data using `@JsonRawValue` annotation.

**Comment by eshxcmhk** [comment]
@cowtowncoder It will get the correct format by this. But the tag of 'data' is missing, even use annotation like:
	@JsonProperty("data")
or:
	@JacksonXmlElementWrapper(useWrapping = true)
	@JacksonXmlProperty(localName = "data")
What I can think of is that I can encoding the content of 'data' to solve it.
Is there a way to use the API to solve this problem?

**Comment by cowtowncoder** [comment]
@eshxcmhk Wrapping only applies to `Collection` valued properties so that will not make difference.
But I am not sure what exactly is missing: from example, output should look something like (without indentation)

```xml
<RPCResult>
  <result>4</result>
  <message>message contents</message>
  <data>... pre-encoded contents of `data` property ... </data>
</RPCResult>
```

If this is not happening that could be a bug.

**Comment by eshxcmhk** [comment]
@cowtowncoder Yes, when I use @JsonRawValue annotation, I got the result:
```xml
<RPCResult>
  <result>4</result>
  <message>message contents</message>
  <Gps><gpsx>0.0</gpsx><gpsy>0.0</gpsy></Gps><!-- there is no tag of 'data' wrapped -->
</RPCResult>
```

**Comment by cowtowncoder** [comment]
Ok. Could you file a new issue, adding POJO with annotation, output.
It sounds like there might be a flaw. New issue makes sense since it's bit different from this one.

**Comment by eshxcmhk** [comment]
@cowtowncoder Ok, I will do it now
