### ISSUE TITLE
how to diable the xml formatting when using it together with spring cloud

### ISSUE THREAD

**Issue by WuDonghong** [FasterXML/jackson-dataformat-xml#268]
I import this jar into my spring-cloud project. And I found my rest controller responses are automatically converted to xml-format rather than json-format. Could anyone help me how to disable this feature? my spring-cloud version is Dalston.SR1, and the jackson-dataformat-xml version is 2,8.10

**Comment by cowtowncoder** [comment]
This sounds a Spring problem, so please seek advice from spring-cloud project.

Also: for usage questions related to Jackson itself, mailing lists are used:

https://groups.google.com/forum/#!forum/jackson-user

as issue trackers are for, as name implies, for reporting issues.
Mailing lists has many, many more developers, some of who might be able to help.
