### ISSUE TITLE
xmlns namespace attributed as key value pair in generated json

### ISSUE THREAD

**Issue by JayantNayak** [FasterXML/jackson-dataformat-xml#272]
I have a usecase where I need the xmlns namespace attribute as a key value pair in the generated json from xml . But currently I am not able to do so as the namespace is getting ignored.

xml is
<?xml version="1.0" encoding="utf-8"?> <edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx"> <edmx:Reference Uri="../VOC_Core/$metadata"> <edmx:Include Namespace="Org.OData.Core.V1" Alias="Core" /> </edmx:Reference> <edmx:DataServices> <Schema Namespace="EPMSample" xmlns="http://docs.oasis-open.org/odata/ns/edm"> </Schema> </edmx:DataServices> </edmx:Edmx>

generated json
{ "Version":"4.0", "Reference":{ "Uri":"../VOC_Core/$metadata", "Include":{ "Namespace":"Org.OData.Core.V1", "Alias":"Core" } }, "DataServices":{ "Schema":{ "Namespace":"EPMSample" } } }

My code is as follows

XmlMapper xmlMapper = new XmlMapper();
JsonNode node = xmlMapper.readTree(xml.getBytes());
ObjectMapper jsonMapper = new ObjectMapper();
String json = jsonMapper.writeValueAsString(node);
How can I include the xmlns attribute as a key value pair in the json
What all configuration do I need to do so , as to retains the xmlns attribute. ?

**Comment by cowtowncoder** [comment]
Namespace declarations are not attributes but metadata, so parsers do not expose them as attributes (information itself is available, as necessary, but its primary purpose is to define namespace URI to associate with elements and attributes).
As such they will not be exposed via parsers, and can not be automatically added in output.

However... if you really do not care about namespace bindings at all, it is possible to configure underlying XML parsers to disable namespace handling. If so, namespace declarations are not recognized as such but are reported as regular attributes.

Configuration is through `XMLInputFactory.setProperty()`, with property name defined in there (something like `XMLInputFactory.IS_NAMESPACE_AWARE`). You need to construct `XmlMapper` with proper settings (passing `XMLFactory`, I think, which you can configure with input and/or output factory configured to your liking).

**Comment by JayantNayak** [comment]
Thanks @cowtowncoder  for the quick response .  :)
I tried following your suggestion but I am still not able to configure it to get the namespace. :(
Also attached the sample test code.
`
package sampleapp2.sampleapp2;
import java.io.IOException;
import com.fasterxml.aalto.stax.InputFactoryImpl;
import com.fasterxml.aalto.stax.OutputFactoryImpl;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.xml.JacksonXmlModule;
import com.fasterxml.jackson.dataformat.xml.XmlFactory;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;


public class App2 {
	public static void main(String[] args) {
	
		String xml ="<?xml version=\"1.0\" encoding=\"utf-8\"?>"
		+"<edmx:Edmx Version=\"4.0\" xmlns:edmx=\"http://docs.oasis-open.org/odata/ns/edmx\">"
		+	"<edmx:Reference Uri=\"../VOC_Core/$metadata\">"
		+		"<edmx:Include Namespace=\"Org.OData.Core.V1\" Alias=\"Core\" />"
		+	"</edmx:Reference>"
		+	"<edmx:DataServices>"
		+		"<Schema Namespace=\"EPMSample2\" xmlns=\"http://docs.oasis-open.org/odata/ns/edm\"/>"
		+	"</edmx:DataServices>"
		+"</edmx:Edmx>";

		XmlMapper xmlMapper;
		InputFactoryImpl xif = new InputFactoryImpl();
		xif.setProperty(xif.IS_NAMESPACE_AWARE, Boolean.FALSE);
		OutputFactoryImpl xof = new OutputFactoryImpl();
		xof.setProperty(xof.XSP_NAMESPACE_AWARE, Boolean.FALSE);
		xmlMapper = new XmlMapper(new XmlFactory(xif,xof), new JacksonXmlModule());

		try {
			JsonNode node = xmlMapper.readTree(xml.getBytes());
			ObjectMapper jsonMapper = new ObjectMapper();
			String json = jsonMapper.writeValueAsString(node);
			System.out.println(json);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}}

`
I am using the version  jackson 2.9.2 along with aalto-xml 1.0.0 
Could you please check the above code and let me know. If I have missed out on something.

**Comment by cowtowncoder** [comment]
@JayantNayak Code looks correct. One thing to try is to use `woodstox-core` instead of Aalto: I do not remember if Aalto supports non-namespace-aware mode (if not it should throw exception when trying to disable namespace processing).

**Comment by JayantNayak** [comment]
@cowtowncoder 
I checked Aalto  [source code](https://github.com/FasterXML/aalto-xml/blob/master/src/main/java/com/fasterxml/aalto/in/ReaderConfig.java) and found that by default some of the configuration are always true including IS_NAMESPACE_AWARE and disabling it has no effect also . Its strange **that at least the user should get an exception  when trying to disabling them** as you have mentioned earlier.
Anyways I tried with out Aalto and did the following code changes to the xml mapper and now I am able to achieve my purpose
`
XmlMapper xmlMapper;
XMLInputFactory xif = XMLInputFactory.newInstance(); 
xif.setProperty(xif.IS_NAMESPACE_AWARE, false);
XmlFactory xmlFactory = new XmlFactory(xif);
xmlMapper = new XmlMapper(xmlFactory, new JacksonXmlModule());
`
Thanks for the help I am closing this issue. 👍

**Comment by cowtowncoder** [comment]
@JayantNayak Ok I'll add an issue for Aalto issue tracker for this.

Also: make sure to specifically use `Woodstox` and NOT the Stax implementation JDK comes with (`sjsxp`). While `sjsxp` may work for some use cases it has known bugs, is slower, and does not implement all Stax functionality. So using it is likely to cause more problems down the line.
