### ISSUE TITLE
Deserialization xml with mixed unwraped array elements

### ISSUE THREAD

**Issue by slavniyteo** [FasterXML/jackson-dataformat-xml#275]
I found a bug with deserialization unwrapped arrays. 

If xml elements are ordered like:
```xml
<root>
    <arrayElement/>
    <otherProperty/>
    <arrayElement/>
</root>
```
then first `<arrayElement/>` is ignored and array contains the second element only.

**jackson version:** 2.9.3

---

I wrote the test case (sorry for using Lombok, I wanted to omit boilerplate code and do not write many `equals` methods).

**POJO definition:**
```java
package com.example.xml;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import lombok.AllArgsConstructor;
import lombok.Data;

import java.util.List;

@JacksonXmlRootElement
@Data
public class Root {

    @JacksonXmlProperty(localName = "cat")
    @JacksonXmlElementWrapper(useWrapping = false)
    public List<Cat> cats;

    @JacksonXmlProperty(localName = "dog")
    public Dog dogs;

    // Nested classes

    @Data
    @AllArgsConstructor
    public static class Dog {

        @JacksonXmlProperty(isAttribute = true)
        public String name;
    }

    @Data
    @AllArgsConstructor
    public static class Cat {

        @JacksonXmlProperty(isAttribute = true)
        public String name;
    }
}
```

**Test class:**
```java
package com.example.xml;

import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import org.junit.Test;
import java.util.ArrayList;
import static org.junit.Assert.assertEquals;

public class DeserializationTest {

    @Test
    public void contextLoads() throws Exception {
        Root actual = xmlMapper()
                .readValue(XML, Root.class);
        assertEquals(EXPECTED, actual);
    }

    private static final String XML = "<root>" +
                                      "    <cat name=\"first cat\"/>" +
                                      "    <dog name=\"first dog\"/>" +
                                      "    <cat name=\"second cat\"/>" +
                                      "</root>";

    private static final Root EXPECTED = new Root() {{
        cats = new ArrayList<Cat>() {{
            add(new Cat("first cat"));
            add(new Cat("second cat"));
        }};
        dogs = new Dog("first dog");
    }};

    private static XmlMapper xmlMapper() {
        final XmlMapper result = new XmlMapper();
        return result;
    }
}
```

**Output:**
```
java.lang.AssertionError: 
Expected :Root(cats=[Root.Cat(name=first cat), Root.Cat(name=second cat)], dogs=Root.Dog(name=first dog))
Actual   :Root(cats=[Root.Cat(name=second cat)], dogs=Root.Dog(name=first dog))
```

As you can see, `first cat` is absent in deserialized object.

---

I saw #201, but it is not this bug about.

**Comment by slavniyteo** [comment]
I looked inside.

I think the problem is that `MethodProperty.deserializeAndSet` uses method `CollectionDeserializer.deserialize(JsonParser, DeserializationContext)` but not `CollectionDeserializer.deserialize(JsonParser, DeserializationContext, Collection<Object>)`.

**Comment by cowtowncoder** [comment]
No, this is a feature at this point. You can not arbitrarily split elements of an array around other properties: this does not and will not work, by default.

But as you pointed out, you can work around this problem by defining setter to do coalescing.

**Comment by mkhan-coremedia** [comment]
Great, it helped me with some other kind of problem, for me wrapping was not working if I had a child of the same name and same attribute multiple times, it was only taking the first element of the list and leaving others.

**Comment by naXa777** [comment]
Any alternatives out there to Jackson XML deserialization library? I'm looking for a library that handles unwrapped lists (and their child elements) correctly, not ignoring them like Jackson does.

**Comment by cowtowncoder** [comment]
@naXa777 Jackson does not ignore unwrapped lists when using

```
@JacksonXmlElementWrapper(useWrapping = false)
```

annotation.

**Comment by mkuss** [comment]
A simpler workaround is using an additional `@JsonMerge` annotation on the lists like

```
    @JacksonXmlProperty(localName = "cat")
    @JacksonXmlElementWrapper(useWrapping = false)
    @JsonMerge
    public List<Cat> cats;
```

(At least in my use case this did the trick)

**Comment by cowtowncoder** [comment]
Thank you for sharing, @mkuss
