### ISSUE TITLE
Similar "JsonFormat.Feature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT" but for composite types

### ISSUE THREAD

**Issue by paroxysm** [FasterXML/jackson-dataformat-xml#283]
Hey guys,
So awhile ago an issue was fixed with the mapper de-serializing empty string types such as `<first/>` into a null, as opposed to a "".

There's also a similar issue affecting composite types as well.
Consider pseudo-xsd:
```
<complexType name="Parent">
  <element name="child" type="Child" maxOccurs="0"/>
</complexType>

<complexType name="Child">
 <element name="member1"/>
 <element name="member2"/>
 <element name="member3"/>
...
</complexType>
```

If maven-jaxb-plugin generate POJOs for this, I get pseudo-java:
```
@XmlType( name="Parent") class Parent {  @XmlElement(name - "child") List<Child> child }
@XmlType(name="Child") class Child { ... }
```

Given an XmlMapper initialized as so:
```
XmlMapper mapper = new XmlMapper();
AnnotationIntrospector introspector= new JaxbAnnotationIntrospector(TypeFactory.defaultInstance());
mapper.setAnnotationIntrospectors(introspector, introspector);
```

If I try to deserialize:
`<Parent/>`

I'll end up with a null object.
However, one would expect to end up with a non-null instance of "Parent", that has an empty or null list of "Child" 

EDIT: Just realized I created a duplicate of #209

**Comment by cowtowncoder** [comment]
In theory, this is what `2.9` feature for configurable nulls:

https://github.com/FasterXML/jackson-databind/issues/1402

should allow. Unfortunately there seems to be something preventing it with XML; I will be filing a new issue for that.
And yes, this is same as #209, so closing.
