### ISSUE TITLE
`@JsonSetter(nulls=...)` not working with XML

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-xml#285]
(note: follow-up from #209)

Ok it looks like feature added in 2.9 for configurable null handling:

https://github.com/FasterXML/jackson-databind/issues/1402

does not quite work with XML. Need to figure out why, and fix it.

**Comment by markaren** [comment]
The following seems to work as expected

```kotlin
class Real

    class ScalarVariable {

        @JsonSetter(nulls = Nulls.AS_EMPTY)
        @JacksonXmlProperty(localName = "Real")
        var real: Real? = null

    }

    @Test
    fun test2() {

        val xml = """
            <ScalarVariable >
                <Real />
             </ScalarVariable >
            """

        val mapper = XmlMapper().apply {
            registerModule(KotlinModule())
        }
        val variable = mapper.readValue<ScalarVariable>(xml)

        Assert.assertNotNull(variable.real)

    }
```

Removing

```java
@JacksonXmlProperty(localName = "Real")
```

And the test will fail

**Comment by cowtowncoder** [comment]
@markaren thank you for testing it.

I actually noticed the same: I have a more elaborate case that uses generic type, and that is problematic for some reason... but simple POJO dependency does work.

**Comment by cowtowncoder** [comment]
Will work better in 2.9.6 as well.

**Comment by PaulBenn** [comment]
> * Make start/end tag also coerce to `null` with same feature (seems reasonable)

Hi, is this planned for a future milestone?

`Nulls.AS_EMPTY` does not support the following form of empty collection yet (as of version 2.11):

```<MyList></MyList>```

**Comment by cowtowncoder** [comment]
@PaulBenn You may try this against `2.12.0-rc1` (released couple of days ago). I think handling should result in empty `List` with 2.12.0, regardless of this configuration (that is, should not even need to set it).
