### ISSUE TITLE
Serializing `Map` key starting with `/` (or other character not valid in XML name)

### ISSUE THREAD

**Issue by tyler-cloud-elements** [FasterXML/jackson-dataformat-xml#288]
Version: 2.7.9 (but occurs with 2.9.5)
Woodstox: 4.4.1

In adding support for XML to our JSON based platform using this lovely library, we are having trouble generating valid XML for swagger paths. Short example:

```
{
  "paths": {
    "/field": "value"
  }
}
```
-> ```<HashMap><paths></field>value<//field></paths></HashMap>```

And passing through a validator throws 
>The element type "paths" must be terminated by the matching end-tag "</paths>"

**Quick sample**:

```java
Map<String, Object> xmlObject = new HashMap<String, Object>();
Map<String, Object> firstLevel = new HashMap<String, Object>();
firstLevel.put("/field", "value");
xmlObject.put("paths", firstLevel);

System.out.println(new XmlMapper(new JacksonXmlModule()).writeValueAsString(xmlObject));
```

-----------
I've looked around, but haven't seen anything to resolve such case. Anyone run into this before or is this a bug?

**Comment by cowtowncoder** [comment]
Ok, first things first: `Map`s do not work well with this module (and with XML tools in general, require mapping to other types first). So compared to POJOs, where property names are (I think) escaped to avoid use of XML invalid name characters, no special handling is added for `Map` keys.
But unfortunately I don't think this can be solved well in general case: there is no good mechanism for both escaping and unescaping on deserialization. It may be possible to do one-way translation (possibly by translating all "weird" characters as something like underscore character), but no way to reliably deserialize them back.

So, it may make sense to try to avoid using `Map`s; or, possibly registering custom serializer for `Map` values, with whatever conversion logic would seem to make sense.

**Comment by cowtowncoder** [comment]
I think this is same as #244: real problem, need to figure out a solution. Can not escape names in XML so probably need different kind of serialization for Maps.
