### ISSUE TITLE
Allow stax2-api 4.1

### ISSUE THREAD

**Issue by markwoon** [FasterXML/jackson-dataformat-xml#300]
In jackson-dataformat-xml 2.9.6 the OSGI `Import-Package` directive in `MANIFEST.MF` limits stax2 to versions 3.1 - 4.  Please expand it to allow 4.1 as well.

**Comment by cowtowncoder** [comment]
@markwoon So what would be the appropriate change? Is there an easy way to test things work, both smoke-test (will load and not fail) and that usage works? I don't use OSGi myself for anything so I rely on others knowledge here, and with patches I want to be especially careful.

**Comment by markwoon** [comment]
@cowtowncoder Unfortunately I'm mainly an OSGI consumer.  I also don't use maven much.

That said, adding the following to `pom.xml` seems to make the right changes to allow stax2 3.1.4 and up:

```
    <plugin>
      <groupId>org.apache.felix</groupId>
      <artifactId>maven-bundle-plugin</artifactId>
      <extensions>true</extensions>
      <configuration>
        <instructions>
          <Bundle-SymbolicName>${project.groupId}.${project.artifactId}</Bundle-SymbolicName>
          <Import-Package>
            org.codehaus.stax2;version="[3.1.4,)",
            org.codehaus.stax2.io;version="[3.1.4,)",
            org.codehaus.stax2.ri;version="[3.1.4,)",
            *
          </Import-Package>
        </instructions>
      </configuration>
    </plugin>
```

From a maintenance standpoint, this is probably not ideal because you'll have to update the list of packages whenever that changes.

**Comment by stbischof** [comment]
I've the same Problem.

please update your dependency in pom to 4.1.4 or describe imports manually as explained.

**Comment by cowtowncoder** [comment]
@stbischof I am not quite sure what you mean by the comment above.

With 2.10 I think we can and should increase version baseline to 4.1 for stax2-api, for simplicity.
I don't think it is a good idea to make significant changes in patch release however.

**Comment by cowtowncoder** [comment]
Stax2-api dependency has been updated to 4.1 (and later) in 2.10+.
