### ISSUE TITLE
Force deserialization of @JacksonXMLText as CDATA section

### ISSUE THREAD

**Issue by winklehner** [FasterXML/jackson-dataformat-xml#303]
We are using JacksonXML to parse XML provided from Pubmed. Unfortunately it stopped working as Pubmed started to put HTML and MathML section into text elements. e.g.

```
<AbstractText>
<b>Some</b>
</AbstractText>

```
I know this should be wrapped correctly in a CDData section but its not. Would it be possible for JacksonXML if we use the @JacksonXmlText and @JacksonXmlCData annotation on the String abstractText field to automatic stop parsing any special elements and considering anything in-between 
< AbstractText > and < /AbstractText > as text without pre-processing the XML and wrapping everything in CDATA?

**Comment by cowtowncoder** [comment]
No, this is not something that is possible unfortunately. Jackson uses underlying Stax parser, and XML parser are to decode content as they see and have no means (that I know of) to somehow expose undelrying content (without parsing they wouldn't really know what would constitute end of just "raw" segment).
