### ISSUE TITLE
how to serialize Java bean  with empty element to xml  with start and end tag instead of self-closing tag

### ISSUE THREAD

**Issue by sun152121** [FasterXML/jackson-dataformat-xml#304]
when serialize to xml,I need  `<OrderId><OrderId/>`   instead of  `<OrderId/>` ,how to do it?

**Comment by cowtowncoder** [comment]
In future, please use mailing lists for usage questions:

https://groups.google.com/forum/#!forum/jackson-user

As to the question: XML module has no control over whether underlying Stax writer chooses one presentation or the other: these are identical from XML logical content perspective. There should be no difference and any client that only deals with one and not the other is somewhat broken.

Having said that, if you use Woodstox as Stax implementation, there is a setting:

https://medium.com/@cowtowncoder/configuring-woodstox-xml-parser-woodstox-specific-properties-1ce5030a5173

`WstxOutputProperties.P_AUTOMATIC_END_ELEMENTS`

disabling of which should do what you need. You need to pass `XMLOutputFactory` to `XmlFactory` when constructing `XmlMapper`. README should now have a mention of how to do that.

I hope this helos.

**Comment by AniFengx** [comment]
I set the property but it doesn't work.
code : 
```
CorpGoodsReport g = new CorpGoodsReport();
XmlMapper xmlMapper = new XmlMapper();
xmlMapper.getFactory().getXMLOutputFactory().setProperty(WstxOutputProperties.P_AUTOMATIC_END_ELEMENTS, false);
xmlMapper.enable(SerializationFeature.INDENT_OUTPUT);
xmlMapper.configure(ToXmlGenerator.Feature.WRITE_XML_DECLARATION, true);
xmlMapper.writeValue(new FileOutputStream("a.xml"), g);
```
But if field is null ,the xml tag will be <FIELD_CHAR3/> ，if field is "" ,XmlMapper can generate normally  
 <FIELD_CHAR1></FIELD_CHAR1>.
Do you have any idea can fix it?

**Comment by cowtowncoder** [comment]
@AniFengx One thing to verify is to ensure `Woodstox` is ued. But I'll see if I can reproduce this.

**Comment by cowtowncoder** [comment]
Actually, no, if "" is written, underlying XML parser will not produce empty element as that is explicit indication that empty element is not to be used. So that won't work.

Given that semantically `<tag></tag>` and `<tag/>` have no difference, I don't think this is something databind library needs to provide, so I will close the issue.

**Comment by anand1st** [comment]
I know this issue is closed. But there are cases when the XML parser on a third party application is forcing me to generate XML with `<tag></tag>` instead of `<tag/>`. And searching for a solution to this leads me to this site in google.

I'm just putting out my solution that worked for me using Woodstox in my problem.
```
var outputFactory = new WstxOutputFactory();
outputFactory.setProperty(WstxOutputProperties.P_USE_DOUBLE_QUOTES_IN_XML_DECL, Boolean.TRUE);
// The property below does it for me
outputFactory.setProperty(WstxOutputProperties.P_OUTPUT_EMPTY_ELEMENT_HANDLER,
        (EmptyElementHandler) (prefix, localName, nsURI, allowEmpty) -> false);
var xmlMapper = new XmlMapper(new WstxInputFactory(), outputFactory);
xmlMapper.enable(SerializationFeature.INDENT_OUTPUT);
xmlMapper.configure(ToXmlGenerator.Feature.WRITE_XML_DECLARATION, true);
xmlMapper.configure(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS, true);
xmlMapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);
```
With the above, I could get `<tag></tag>` instead of `<tag/>`

**Comment by cowtowncoder** [comment]
@anand1st Thank you for sharing your solution. Did setting `WstxOutputProperties.P_AUTOMATIC_END_ELEMENTS` to `Boolean.FALSE` not work for you?

**Comment by anand1st** [comment]
@cowtowncoder No, it didn't work for me. I keep getting self-closed tags.

**Comment by cowtowncoder** [comment]
@anand1st Odd. That would either mean that setting did not take effect (or there's a bug in Woodstox), or that serialization was somehow explicitly calling `writeEmptyElement()`.
Glad you find out a way that works but I think I'll check out Woodstox' testing.

**Comment by cowtowncoder** [comment]
D'oh. My apologies: this is not the setting I was thinking for. (END != EMPTY).

The real setting is

    WstxOutputProperties.PROP_AUTOMATIC_EMPTY_ELEMENTS

which should work, although I do not see tests verifying its working (which is bad).

**Comment by cowtowncoder** [comment]
Added simple test to verify basic working of `XMLOutputFactory2.P_AUTOMATIC_EMPTY_ELEMENTS` in Woodstox, for what that is worth.

**Comment by anand1st** [comment]
Thank you. Confirmed that the following does the trick.
`outputFactory.setProperty(XMLOutputFactory2.P_AUTOMATIC_EMPTY_ELEMENTS, Boolean.FALSE);`.
