### ISSUE TITLE
Unbound namespace URI ''  when using isAttribute=true on JacksonXmlProperty

### ISSUE THREAD

**Issue by fredrik-rambris** [FasterXML/jackson-dataformat-xml#311]
When streaming beans and producing XML I get an exception saying Unbound namespace URI '' when I am using @JacksonXmlProperty(isAttribute=true).

```java
@JacksonXmlProperty(isAttribute = true)
private String source="ECOM";
private Member member;
```
Using Jackson 2.9.7 with woodstox 5.0.3.

If I set 
`xmlOutputFactory.setProperty(XMLOutputFactory.IS_REPAIRING_NAMESPACES, true);`
The code works but then the produced document has no xmlns.

[A gist displaying the failing code](https://gist.github.com/fredrik-rambris/bcf07f98a7a3fe2a0a606be950fa0fad)

**Comment by cowtowncoder** [comment]
Interesting. You are right, there is an exception, and unexpected one at that.
I would have thought that works fine, and it should I think. I'll see if I can figure out what causes it, fix.

**Comment by cowtowncoder** [comment]
Also interesting: fails on 2.x, but passes on 3.0.0-SNAPSHOT for some reason. Hmmh.

**Comment by cowtowncoder** [comment]
Filed #326 as replacement.
