### ISSUE TITLE
Add comment regarding jaxb api lib in Java 11 and later

### ISSUE THREAD

**Issue by ST-DDT** [FasterXML/jackson-dataformat-xml#312]
If you try to run Jackson XMLMapper on Java 11 and later you will get an exception because jaxb is no longer on the classpath by default.

Please add a short info to the Readme that states that you will need to add the following to your pom as well.

````xml
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
</dependency>
````

I don't know whether this is necessary when using woodstox, I assume it is still needed for the annotations.

**Comment by cowtowncoder** [comment]
Is this still an issue with 2.10 or 2.11?

**Comment by ST-DDT** [comment]
I currently don't have access to a project that uses XML that I could use to test this.

If I read the POM correctly :

- https://github.com/FasterXML/jackson-dataformat-xml/blob/2379780e2ac929c34d12644e40b72d855e7727ce/pom.xml#L59-L64 (3.0-SNAPSHOT)

- https://github.com/FasterXML/jackson-dataformat-xml/blob/e909c684f89bcd34f4734e2c419c52362ce6b432/pom.xml#L103-L108 (2.11)

Then it's only added to tests, but not inherited.

See also the comment added to the pom:

https://github.com/FasterXML/jackson-dataformat-xml/blob/e909c684f89bcd34f4734e2c419c52362ce6b432/pom.xml#L99-L102

**Comment by cowtowncoder** [comment]
I think this is related to module definitions, and will be improved in 2.12.
I am open to better README, but would need a contribution.
