### ISSUE TITLE
Empty tag does not result in instantiation/intializing of using when using XmlMapper

### ISSUE THREAD

**Issue by itisvamsi** [FasterXML/jackson-dataformat-xml#316]
Hi , I am sending the xml request mentioned below and following is the object hierarchy
productInstanceDataJoin --> productInstanceSummaryJoin--> productSummaryJoin

![image](https://user-images.githubusercontent.com/12539710/47068617-6329f480-d20a-11e8-8731-16d219dea4cf.png)

I am using XMLMapper to construct the object using readValue(xmlString, Object). I am using version 2.9.4 version and when i am doing that only the first 2 objects are  constructed and the leaf object(productSummaryJoin) is set to null (This also should get initialized).

Could you please let me know  if there is any fix available for this or how to solve this issue?

**Comment by itisvamsi** [comment]
<productInstanceDataJoin>
      <productInstanceSummaryJoin>
         <productSummaryJoin></productSummaryJoin>
      </productInstanceSummaryJoin>
   </productInstanceDataJoin>

**Comment by cowtowncoder** [comment]
I think this will be fixed in 2.12.0 along with many other issues, although without actual full test (would need POJOs in question) hard to say for sure.
May be reopened with unit test; will close assuming issue is actually fixed (and fix to be included in 2.12.0 as per above, not released yet).
