### ISSUE TITLE
No annotation for create  a xml head line

### ISSUE THREAD

**Issue by BBSee** [FasterXML/jackson-dataformat-xml#317]
...

**Comment by BBSee** [comment]
My analysis program need the xml file with head line -<?xml version="1.0" encoding="UTF-8"? >,but there is no annotation for this,so ,what could I do to add this line to my xml file?

**Comment by cowtowncoder** [comment]
XML declaration should already be written, especially if you use either Woodstox or Aalto as the XML library. So I would need a test case to show if it is not.

But to force writing "raw" text in output, you can use `JsonGenerator.writeRaw(...)`.

**Comment by cowtowncoder** [comment]
I don't think I'd want an annotation for this, but I plan on adding a mechanism to write other decorations (XML declaration, DOCTYPE) in 2.12; this would possibly be handled by that.
