### ISSUE TITLE
unnecessary xmlns="" in the root element

### ISSUE THREAD

**Issue by rgururaj** [FasterXML/jackson-dataformat-xml#32]
ObjectMapper xmlMapper = new XmlMapper();
String xml = xmlMapper.writeValueAsString(new Simple());

and with POJO like:

public class Simple {
    public int x = 1;
    public int y = 2;
}

you would get something like:

<pre><code>&lt;Simple xmlns=""&gt;
  &lt;x&gt;1&lt;/x&gt;
  &lt;y&gt;2&lt;/y&gt;
&lt;/Simple&gt;
</code></pre>

There is a xmlns="" attribute at the root element, which was not expected.
Using version 2.0.4 (dataformat-xml) with 2.0.5 (core)

**Comment by lisadesouza89** [comment]
Can someone confirm what the recommended way to solve this is?

**Comment by cowtowncoder** [comment]
Using Stax implementation other than one that is bundled with JDK: both Woodstox and Aalto work in a way that does not produce this extra (harmless) namespace declaration.

**Comment by dewthefifth** [comment]
In general, and according to the XML standard including xmlns="" should NOT change the meaning of the XML tags. That said, SAX builders (for example with JDOM2) appear to get upset if the empty namespace is declared.

**Comment by cowtowncoder** [comment]
Thank you for additional notes.

**Comment by pradeepkusingh** [comment]
i am seeing same  issue with Spring boot 1.4.1 and woostox 1.4.x, it is generating blank name space. how to fix this ?

**Comment by cowtowncoder** [comment]
@pradeepkusingh I have not seen Woodstox do this ever, so a reproduction would be needed: stand-alone one, not via Spring Boot. More commonly this is due to some other Stax implementation being used so you may want to double check to try to see what implementation is being used.
If you can reproduce this with Woodstox 4.0 with such a test please file a new issue as this one is closed.

**Comment by JayantNayak** [comment]
I have a usecase where I need  the xmlns namespace attribute  as a key value pair  in the generated json from xml .  But currently I am not able to do so as the namespace is getting ignored.


xml is 
`<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
	<edmx:Reference Uri="../VOC_Core/$metadata">
		<edmx:Include Namespace="Org.OData.Core.V1" Alias="Core" />
	</edmx:Reference>
	<edmx:DataServices>
		<Schema Namespace="EPMSample" xmlns="http://docs.oasis-open.org/odata/ns/edm">
		</Schema>
	</edmx:DataServices>
</edmx:Edmx>
`

generated json 
`{  
   "Version":"4.0",
   "Reference":{  
      "Uri":"../VOC_Core/$metadata",
      "Include":{  
         "Namespace":"Org.OData.Core.V1",
         "Alias":"Core"
      }
   },
   "DataServices":{  
      "Schema":{  
         "Namespace":"EPMSample"
      }
   }
}`

My code is as follows

XmlMapper xmlMapper = new XmlMapper();
JsonNode node = xmlMapper.readTree(xml.getBytes());
ObjectMapper jsonMapper = new ObjectMapper();
String json = jsonMapper.writeValueAsString(node);
How can I include the xmlns attribute as a key value pair in the json
What all configuration do I need to do so , as to retains the xmlns attribute. ?

**Comment by cowtowncoder** [comment]
@JayantNayak please do not add comments on closed issues.

For usage questions, please use mailing `jackson-users`.

**Comment by roridedi** [comment]
Is there an annotation associated with Stax?
