### ISSUE TITLE
UnrecognizedPropertyException when using JsonSubTypes/XmlElements on interface field

### ISSUE THREAD

**Issue by blay09** [FasterXML/jackson-dataformat-xml#321]
I'm trying to load an xml with a field that's bound to an interface, where the implementation chosen should depend on the name of the tag.

Hope this is not just a simple user error. I've seen people use it this way for lists and it seems to have worked for them, but I've also noticed that lists don't seem to care about the child tag names at all.

## Example
Simple use-case: I want the `iface` field to map to either `InterfaceImplOne` or `InterfaceImplTwo` depending on which tag is present. Basically `<xs:choice>` in XML schema.

```java
public class InterfaceField {

    @Test
    public void loadUsingJacksonAnnotations() throws IOException {
        XmlMapper mapper = new XmlMapper();
        RootElementUsingJackson root = mapper.readValue("<rootElementUsingJackson><interfaceImplOne /></rootElementUsingJackson>", RootElementUsingJackson.class);
        assertThat(root.iface).isInstanceOf(InterfaceImplOne.class);
    }

    @Test
    public void loadUsingJaxbAnnotations() throws IOException {
        XmlMapper mapper = new XmlMapper();
        mapper.registerModule(new JaxbAnnotationModule());
        RootElementUsingJAXB root = mapper.readValue("<rootElementUsingJAXB><interfaceImplOne /></rootElementUsingJAXB>", RootElementUsingJAXB.class);
        assertThat(root.iface).isInstanceOf(InterfaceImplOne.class);
    }

    @Test
    public void loadUsingNativeJaxb() throws JAXBException {
        JAXBContext context = JAXBContext.newInstance(RootElementUsingJAXB.class);
        Unmarshaller unmarshaller = context.createUnmarshaller();
        RootElementUsingJAXB root = (RootElementUsingJAXB) unmarshaller.unmarshal(new StringReader("<rootElementUsingJAXB><interfaceImplOne /></rootElementUsingJAXB>"));
        assertThat(root.iface).isInstanceOf(InterfaceImplOne.class);
    }

    public static class RootElementUsingJackson {
        @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.WRAPPER_OBJECT)
        @JsonSubTypes({
                @JsonSubTypes.Type(value = InterfaceImplOne.class, name = "interfaceImplOne"),
                @JsonSubTypes.Type(value = InterfaceImplTwo.class, name = "interfaceImplTwo")
        })
        public Interface iface;
    }

    @XmlRootElement
    public static class RootElementUsingJAXB {
        @XmlElements({
                @XmlElement(name = "interfaceImplOne", type = InterfaceImplOne.class),
                @XmlElement(name = "interfaceImplOne", type = InterfaceImplOne.class)
        })
        public Interface iface;
    }

    public interface Interface {
    }

    public static class InterfaceImplOne implements Interface {
    }

    public static class InterfaceImplTwo implements Interface {
    }

}
```

## What I expected to happen:
All three tests pass, and if I were to put `<interfaceImplTwo />` in the XML it would create an instance of that class instead.

## What actually happened:
Only the `loadUsingNativeJaxb` test passed, the other two fail due to `UnrecognizedPropertyException`:
```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "interfaceImplOne" (class org.eiradir.server.InterfaceField$RootElementUsingJAXB), not marked as ignorable (one known property: "iface"])
 at [Source: (StringReader); line: 1, column: 43] (through reference chain: org.eiradir.server.InterfaceField$RootElementUsingJAXB["interfaceImplOne"])

	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at org.eiradir.server.InterfaceField.loadUsingJaxbAnnotations(InterfaceField.java:33)
```

Judging from what I've seen in the debugger it's correctly creating the deserializer for the interface field, but then errors out before using it due to the `UnrecognizedPropertyException`.

Marking the class as `@JsonIgnoreProperties` will prevent the exception, but the field will remain null.

## Versions
jackson-dataformat-xml: 2.9.7
jackson-module-jaxb-annotations: 2.9.7

**Comment by blay09** [comment]
I tried specifying aliases using `@JsonAlias({"interfaceImplOne", "interfaceImplTwo"})` - this prevents the `UnrecognizedPropertyException` but the field remains `null`. The `AsWrapperTypeDeserializer` is being created for the interface field, but its `_deserialize` function is never called.

**Comment by cowtowncoder** [comment]
This is not how Jackson Polymorphic handling works: even if JAXB annotations are used the choices of Type Id inclusion do not include "combine property name and type id" choice -- Jackson is not a JAXB implementation.

There is already an issue to request supporting this feature -- #197 -- so closing this issue as a duplicate.

To see kind of structure Jackson expects, it is usually best to start by serialization, have a look at what is being produced. Jackson's contract is that it should be able to read structure it writes -- but there is no guarantee that arbitrary XML structures are mappable.
