### ISSUE TITLE
How can I extend FromXmlParser to  parse element attributes into a pseudo property(like '$attr')

### ISSUE THREAD

**Issue by limer2** [FasterXML/jackson-dataformat-xml#338]
The requirement is converting xml into json as blew:
`
<book rank="1">
  <name>book name</name>
  <price>10</price>
</book>
`
=>
`
{
  "$attr": {
    "rank": 1
  },
  "name": "book name",
  "price": 10
}
`

Any helpful tips are welcome.

**Comment by cowtowncoder** [comment]
First of all, you do not extend `FromXmlParser`, as that is just the low level converter from XML events into tokens, to use by databind.

But as importantly, please ask usage questions on mailing list: issue tracker is for reporting problems:

https://groups.google.com/forum/#!forum/jackson-user
