### ISSUE TITLE
url in pom.xml not reachable / outdated?

### ISSUE THREAD

**Issue by Riggs333** [FasterXML/jackson-dataformat-xml#341]
The current value for `url` in the `pom.xml` (http://wiki.fasterxml.com/JacksonExtensionXmlDataBinding) is not reachable:

https://github.com/FasterXML/jackson-dataformat-xml/blob/c1787b9060c6b41ef1e9d2e2605e7b76b1335e70/pom.xml#L19

I guess it is outdated and maybe should be replaced by something like
* https://github.com/FasterXML/jackson-dataformat-xml/wiki or
* https://github.com/FasterXML/jackson-dataformat-xml

What do you think?

### Background

The [Gradle Versions Pluing](https://github.com/ben-manes/gradle-versions-plugin/) prints this url in their report looking like this:
```
The following dependencies have later milestone versions:
 - com.fasterxml.jackson.dataformat:jackson-dataformat-xml [2.9.8 -> 2.9.9]
     http://wiki.fasterxml.com/JacksonExtensionXmlDataBinding
```

**Comment by cowtowncoder** [comment]
Thanks! Will fix.

**Comment by cowtowncoder** [comment]
Updated to point to git root for 2.9, 2.10 and master
