### ISSUE TITLE
xml反序列化异常JsonMappingException

### ISSUE THREAD

**Issue by liukex** [FasterXML/jackson-dataformat-xml#346]
com.fasterxml.jackson.databind.JsonMappingException: Invalid definition for property "CommonQueryResultList" (of type Lcom/xzst/kafka/model/technicalinvestigation/result/CommonlyQueryResponse;): Could not find creator property with name 'CommonQueryResultList' (known Creator properties: [PrivoderCode, ServeIdentifier, OperateResult, ResultCount, CommonQueryResultInfo])
 at [Source: java.io.StringReader@3dddefd8; line: 3, column: 1]

springboot 升级2.0.0就正常1.5.3就不行！求大佬给个1.5.3的解决方法

**Comment by cowtowncoder** [comment]
Need a reproduction (unit test), one that does not rely on Spring Boot or other frameworks.

**Comment by liukex** [comment]
已解决是lombok低版本问题。
