### ISSUE TITLE
xmlToBean集合反序列化失败

### ISSUE THREAD

**Issue by liukex** [FasterXML/jackson-dataformat-xml#348]
springboot版本1.5.3
com.fasterxml.jackson.databind.JsonMappingException: Invalid definition for property "CommonQueryResultList" (of type Lcom/xzst/jacksonxml/model/result/CommonlyQueryResponse;): Could not find creator property with name 'CommonQueryResultList' (known Creator properties: [PrivoderCode, ServeIdentifier, OperateResult, ResultCount, CommonQueryResultInfo])
 at [Source: java.io.StringReader@233795b6; line: 3, column: 9]
升级2.0.0问题解决，请问1.5.3怎么解决这个问题？相关代码已上传至码云:
https://gitee.com/liukexin/jacksonxml

**Comment by cowtowncoder** [comment]
Test needed.
