### ISSUE TITLE
XmlBeanSerializer serialzes AnyGetters field even with FilterExceptFilter

### ISSUE THREAD

**Issue by rohitnarayanan** [FasterXML/jackson-dataformat-xml#351]
Version: jackson-dataformat-xml-2.9.9

When using FilterExceptFilter to serialize selected fields, XmlBeanSerializer also serializes the AnyGetter field. The problem seems to be at XmlBeanSerializerBase.serializeFieldsFiltered() line: 292, where it calls _anyGetterWriter.getAndSerialize(). 

On the other hand YAML/JSON serialization works fine because BeanSerializerBase.serializeFieldsFiltered() line: 775, calls _anyGetterWriter.getAndFilter()

**Comment by cowtowncoder** [comment]
Thank you for reporting the problem. One request: while I think I understand issue at high level, would it be possible to have a small reproduction? That makes it easier to not just fix, but verify the fix and guard against regressions?

**Comment by cowtowncoder** [comment]
I went ahead and submitted what seems like a fix, and maybe a test can be added later (databind has tests which might be possible to use as base).
