### ISSUE TITLE
Please help with xsi:nil

### ISSUE THREAD

**Issue by itgeo123** [FasterXML/jackson-dataformat-xml#352]
Hello

I am trying to deserialize an XML using JAckson. All is fine, except when xml element has attribute xsi:nil=true. Then XmlMapper reports errors on irrelevant xml nodes.

How to make Jackson to ignore xsi:nil?
<Location xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\" />\

Thank you!

**Comment by cowtowncoder** [comment]
In future, please use mailing list for usage questions: issue tracker is for reporting bugs and requesting new features (supporting handling of `xsi:nil` seems like a valid feature request).

But as to ignoral, try using `@JsonIgnore({ "nil" })`?

**Comment by cowtowncoder** [comment]
Created #354 which covers this problem as well.
