### ISSUE TITLE
Support mapping `xsi:nul` marked elements as `null`s (`JsonToken.VALUE_NULL`)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-xml#354]
Although XML specification does not specify semantics for `xsi:nil` (with appropriate namespace), XML Schema specification does, and so some Java XML libraries (including JAXB) support mapping it into `null`s.
(there is the related question of generation/writing, but this issue covers only read side).

It would be good if Jackson did same mapping automatically.

For background, see

* #89 (nil like JAXB)
* #184 (for `BigDecimal` etc values)
* #293 (nil for Collections)
* #353 (nil in Collections)

**Comment by cowtowncoder** [comment]
Note: one follow-up task, #359 -- but closed for 2.x

**Comment by henrik242** [comment]
@cowtowncoder I have a test that's failing after upgrading to 2.10.x.  It worked fine with 2.9.x. Any idea if this issue is related, and what I can do to fix it?

The test (kotlintest):
```
data class Silly(val hey: String? = null, val ho: String? = null)

"should encode inner tag with unexpected nil attribute" {
        val xml = """
            <Silly xmlns:a="http://www.w3.org/2001/XMLSchema-instance" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
                <a:Hey i:nil="true"/>
                <a:Ho>to</a:Ho>
            </Silly>"""

        val res = xml.parseXml<Silly>()

        res shouldBe Silly("", "to")
    }
```

The failure:
```
org.opentest4j.AssertionFailedError: expected: Silly(hey=, ho=to) but was: Silly(hey=null, ho=null)
Expected :Silly(hey=, ho=to)
Actual   :Silly(hey=null, ho=null)
```

The `parseXml()` implementation:
```
private fun xmlFactory() = XmlFactory(newInstance().apply {
        setProperty(IS_NAMESPACE_AWARE, true)
})

private val jacksonXmlModule = JacksonXmlModule().apply {
        setDefaultUseWrapper(false)
        setXMLTextElementName(TEXT_CONTENT)
}

private fun createMapper() = XmlMapper(xmlFactory(), jacksonXmlModule)
        .registerKotlinModule()
        .configure(ACCEPT_CASE_INSENSITIVE_PROPERTIES, true)
        .configure(FAIL_ON_UNKNOWN_PROPERTIES, false)
        .configure(ACCEPT_SINGLE_VALUE_AS_ARRAY, true)
        .configure(ACCEPT_EMPTY_STRING_AS_NULL_OBJECT, true)

inline fun <reified T : Any> String.parseXml(): T = createMapper().readValue(this, T::class.java)
```

**Comment by henrik242** [comment]
It works if I replace the `http://www.w3.org/2001/XMLSchema-instance` namespace with something else. Is there a way of disabling this feature?  I guess this is related to https://github.com/FasterXML/jackson-dataformat-xml/issues/358 somehow.

**Comment by cowtowncoder** [comment]
It is probably related to the way `xsi:nil` is detected, yes, although things previously working may just be due to luck (i.e. not necessarily due to explicit support).
I think it's worth creating separate issue; it would be nice if reproduction is in pure Java (since tests can not depend on Kotlin, outside of Kotlin module), but I can probably convert them if need be.

**Comment by henrik242** [comment]
@cowtowncoder Created separate issue with test project in #378
