### ISSUE TITLE
how to remove unnecessary xmlns="" in the child element 

### ISSUE THREAD

**Issue by eonezhang** [FasterXML/jackson-dataformat-xml#355]
Hello guys, 
I want to add namespace to the `root` element, but the `child` elements were attached an empty `xmlns=""`, would you guys help me to remove the redundant bugs.

here is my xml output 
```
<Parent xmlns="http://www.163.com/api/v1">
  <name xmlns="">parent</name>
  <Child xmlns="">
    <age>18</age>
  </Child>
</Parent>
```
I want to remove the xmlns="" in the ` <name xmlns="">parent</name>` and `<Child xmlns="">`

here is my java code 
```
package utils;

import java.io.IOException;

import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLOutputFactory;

import com.ctc.wstx.stax.WstxInputFactory;
import com.ctc.wstx.stax.WstxOutputFactory;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.dataformat.xml.XmlFactory;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;

import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

/**
 * @author eonezhang (eonezhang@gmail.com)
 * @since 2019-08-13-18:30
 */
public class DemoTest {

    public static final String NS = "http://www.163.com/api/v1";

    public static void main(String[] args) throws IOException {
        DemoTest t = new DemoTest();
        t.marshallTest();
    }

    public void marshallTest() throws IOException {
        Parent p = new Parent()
              .setChild(new Child().setAge(18))
              .setName("parent");

        mashall(p);
    }

    private void mashall(Parent p) throws IOException {

        XMLInputFactory ifactory = new WstxInputFactory();
        XMLOutputFactory ofactory = new WstxOutputFactory();
        XmlFactory xf = new XmlFactory(ifactory, ofactory);

        ObjectMapper xmlMapper = new XmlMapper(xf);
        xmlMapper.enable(SerializationFeature.INDENT_OUTPUT);

        xmlMapper.writeValue(System.out, p);
    }

    @Getter
    @Setter
    @Accessors(chain = true)
    @JacksonXmlRootElement(localName = "Parent", namespace = NS)
    public static class Parent {
        @JacksonXmlProperty(localName = "Child")
        private Child child;
        private String name;
    }

    @Getter
    @Setter
    @Accessors(chain = true)
    public static class Child {
        private Integer age;
    }
}
```

and here is my dependencies
```
implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.9.9'
implementation 'com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.9.9'
implementation 'com.fasterxml.woodstox:woodstox-core:5.3.0'
    
```

**Comment by cowtowncoder** [comment]
That is not a bug but feature. Your `Parent` has namespace with non-empty URI; `Child` on the other hand does not, and needs "empty" namespace. That must be declared.

**Comment by jawpio** [comment]
The feature is quite poor IMO, as you must annotate actually EACH field with JacksonXmlProperty with the same namespace.

**Comment by simon04** [comment]
Relates to #18.

**Comment by oooooooz** [comment]
@cowtowncoder 
What's up with [#355 ](https://github.com/FasterXML/jackson-dataformat-xml/issues/355) , and [#324 ](https://github.com/FasterXML/jackson-dataformat-xml/issues/324)  now , Is there any solution? only root element need namespace and xsi:type ,thank you

**Comment by oooooooz** [comment]
@cowtowncoder 
What's up with this and [#324 ](https://github.com/FasterXML/jackson-dataformat-xml/issues/324)  now , Is there any solution? only root element need namespace and xsi:type ,thank you

**Comment by sargaemberke** [comment]
The crucial change is adding your ROOT namespace = "urn:blabla.com:my.msg" to every @JacksonXmlProperty annotation within your Class and ALL its nested classes. This ensures that every element is explicitly associated with the correct namespace. By doing this, you're telling Jackson that all these elements belong to the same namespace as the root element, and therefore, it doesn't need to add the empty namespace declarations.
