### ISSUE TITLE
Coercion of `null` Strings to "" incorrect for 3.0 

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-xml#359]
With rewrite of XML module for 3.0, something is wrong with coercion if null values -- so after #354 resolved this for 2.x, there is now one unit test that only fails for 3.0.
This is due to combination of null->Empty coercion in `XmlMapper`, line ~85:

```java
            _configOverrides.findOrCreateOverride(String.class)
                .setNullHandling(JsonSetter.Value.forValueNulls(Nulls.AS_EMPTY));
```

but removing that line will fail a bunch of other tests that do expect empty String from input to be taken as empty String, not null.

**Comment by cowtowncoder** [comment]
Was fixed.

**Comment by cowtowncoder** [comment]
No, not fixed; test was simply moved under failing. Re-opening.

**Comment by mensinda** [comment]
What is the status of this issue?

**Comment by cowtowncoder** [comment]
@mensinda If there are no updates on the issue, typically nothing has happened.
Note that the issue for upcoming (future) Jackson 3.x, not currently released 2.x versions.

**Comment by mensinda** [comment]
@cowtowncoder Oh, sorry for the noise. I did not check this manually and did not notice the major version bump...
