### ISSUE TITLE
用浏览器访问默认返回xml这是为什么，我想要的默认返回是json

### ISSUE THREAD

**Issue by songjiang951130** [FasterXML/jackson-dataformat-xml#367]
```
[INFO] +- io.swagger:swagger-jaxrs:jar:1.5.3:compile
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.9:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.9.9:compile
```
使用 ``` mvn dependency:tree```发现

**Comment by cowtowncoder** [comment]
I am sorry but I do not understand the issue here.

**Comment by songjiang951130** [comment]
spring boot import jackson-dataformat-xml.then i visit url on the brower, data in the url is formatted in xml . i want data is formatted by json.how to resovle it or configure it in spring boot

**Comment by cowtowncoder** [comment]
This is not Spring Boot issue tracker; please try Spring Boot related tracker or forum.
