### ISSUE TITLE
Jackson's @XmlElementRefs implementation doesn't produce XML

### ISSUE THREAD

**Issue by oliverkuntze** [FasterXML/jackson-dataformat-xml#379]
This issue is a clone of https://github.com/FasterXML/jackson-modules-base/issues/92:

Hey,
either Jackson does not implement JAXB's @XmlElementRefs annotation or the implementation is not producing the corresponding XML.

Given the following no XML element `Type1` or `Type2` gets created. 
Furthermore if setting XmlAccessType.FIELD a XML element `nachrichtentyp` gets created.
Using only one @XmlElementRef without the surrounding @XmlElementRefs the XML is created correctly. Putting one @XmlElementRef into a surrounding @XmlElementRefs the XML is not created correctly. 
So in my opinion it has to be the @XmlElementRefs implementation that has a flaw.
Using the Glassfish RI everything works just fine. 

```java
@XmlAccessorType(XmlAccessType.NONE)
@Builder
@Getter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PACKAGE)
public class Nachricht {
    @XmlElementRefs({
            @XmlElementRef(name = "Type1", type = Type1.class),
            @XmlElementRef(name = "Type2", type = Type2.class)
    })
    private Nachrichtentyp nachrichtentyp;
}
```

where

```java
@XmlTransient
@SuperBuilder
@Getter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PACKAGE)
public abstract class Nachrichtentyp {
    @XmlElement(name = "Service", required = true)
    protected Service service;
}
```

and

```java
@XmlRootElement(name = "Type1")
@XmlAccessorType(XmlAccessType.NONE)
@SuperBuilder
@Getter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PACKAGE)
public class Type1 extends Nachrichtentyp {
    @XmlElement(name = "Something")
    private String something;
}
```

and

```java
@XmlRootElement(name = "Type2")
@XmlAccessorType(XmlAccessType.NONE)
@SuperBuilder
@Getter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PACKAGE)
public class Type2 extends Nachrichtentyp {
}
```

Cheers
Oliver

**Comment by cowtowncoder** [comment]
What is XML output you would expect, and for what input objects?

Jackson is not a JAXB implementation and only tries to map JAXB annotation information into equivalent Jackson functionality, so it is quite possible that some use of `@XmlElementRefs` / `@XmlElementRef` does not map cleanly due to various reasons. But before knowing if this can be improved or not it is necessary to see instances being serialized, and resulting XML output of JAXB implementation vs what Jackson outputs.

**Comment by oliverkuntze** [comment]
The expected output / the output of the JAXB implementation is
```
<Nachricht>
	<Type1>
		<Service/>
		<Something/>
	</Type1>
</Nachricht>
```
and
```
<Nachricht>
	<Type2>
		<Service/>
	</Type2>
</Nachricht>
```
Jackson's output is
```
<Nachricht>
</Nachricht>
```

**Comment by cowtowncoder** [comment]
@oliverkuntze Ok, and with what kind of input value(s) (object(s))?

**Comment by cowtowncoder** [comment]
Will need full reproduction, but I think this refers to something Jackson does not support: "flattening" of type wrapper and property name. Still, output should have more content than empty element so would want to see code that results in output described.

**Comment by cowtowncoder** [comment]
Might be duplicate; or if not (wrt output), would need a reproduction; may be reopened with one.
