### ISSUE TITLE
We have upgraded to jersey 2.29.1 and so jackson to lastest 2.10.0. It seems like XmlMapper still ignores custom serializer.

### ISSUE THREAD

**Issue by kbansod** [FasterXML/jackson-dataformat-xml#387]
We have upgraded to jersey 2.29.1 and so jackson to lastest 2.10.0. It seems like XmlMapper still ignores custom serializer.

My code is exactly as below. It is being invoked via XMLContextResolver. But _serializers = null in XmlMapper object. 

```
@Provider
@Produces({ MediaType.TEXT_XML, MediaType.APPLICATION_XML })
public class XmlMapperContextResolver implements ContextResolver<XmlMapper> {
	
	private Map<String, XmlMapper> xmlMapperMap = new HashMap<>(2); 
	
	@Override
	public XmlMapper getContext(Class<?> type) {
		
			return xmlMapperMap.get("model");
		
	}

	public XmlMapperContextResolver() {
		
		XMLInputFactory xMLInputFactory = XMLInputFactory.newInstance();
		xMLInputFactory.setProperty(XMLInputFactory.SUPPORT_DTD, false); // This disables DTDs entirely for that factory
		xMLInputFactory.setProperty("javax.xml.stream.isSupportingExternalEntities", false); // disable external entities
		
		
		final XmlMapper modelXmlMapper = new XmlMapper(xMLInputFactory);
		final XmlMapper defaultXmlMapper = new XmlMapper(xMLInputFactory);
		
		xmlMapperMap.put("model", modelXmlMapper);
		
		JacksonXmlModule module = new JacksonXmlModule();
		module.setDefaultUseWrapper(false);
		
		module.addSerializer(PropertyMap.class, new PropertyMapSerializer());
		module.addSerializer(OptionList.class, new OptionListSerializer());
		module.addSerializer(MessageBeanList.class, new MessageBeanSerializer());
		module.addSerializer(PropertyPoolMap.class, new PropertyPoolMapSerializer());
		
		module.addSerializer(ModelAndModelGroupList.class, new ModelGroupSerializer());
		
   
		modelXmlMapper.configure(SerializationFeature.INDENT_OUTPUT, true);
		modelXmlMapper.configure(SerializationFeature.WRAP_ROOT_VALUE, true);
		modelXmlMapper.registerModule(module);
		modelXmlMapper.setAnnotationIntrospector(new XmlAnnotationIntrospector());
		modelXmlMapper.setPropertyNamingStrategy(PropertyNamingStrategy.PASCAL_CASE_TO_CAMEL_CASE);
		
	}

}
```

It seems XmlMapper still ignores custom serializer.

I tried using ObjectMapper with SimpleModule, but it does give me desired xml. I get desried xml using JacksonXmlModule, but I want to do some additional work using custom serializer. 

Can someone help me enforce custom serializer in above code? I want to use JacksonXmlModule only.

_Originally posted by @kbansod in https://github.com/FasterXML/jackson-dataformat-xml/issues/41#issuecomment-596191716_

**Comment by cowtowncoder** [comment]
@kbansod I think you might have better luck asking on a Jersey tracker or mailing list, since this is not something `jackson-dataformat-xml` has any control over.

JAX-RS provider itself is from different Jackson repository (`jackson-jaxrs-providers`), but even that can only offer things to be used, and it is up to JAX-RS implementation like Jersey to use it.

Looking at code, I am not sure that it would work at all, however, as `xmlMapperMap` is only initialized in  `XmlMapperContextResolver` constructor. 
 But maybe it does, if `XmlMapperContextResolver` gets instantiated from some external entity.

**Comment by kbansod** [comment]
> @kbansod I think you might have better luck asking on a Jersey tracker or mailing list, since this is not something `jackson-dataformat-xml` has any control over.
> 
> JAX-RS provider itself is from different Jackson repository (`jackson-jaxrs-providers`), but even that can only offer things to be used, and it is up to JAX-RS implementation like Jersey to use it.
> 
> Looking at code, I am not sure that it would work at all, however, as `xmlMapperMap` is only initialized in `XmlMapperContextResolver` constructor.
> But maybe it does, if `XmlMapperContextResolver` gets instantiated from some external entity.

Thanks @cowtowncoder 

If XmlMapper registers my serializer, I will get the desired result. Here is the related issue [https://github.com/FasterXML/jackson-dataformat-xml/issues/41#issuecomment-596191716](url)

**Comment by cowtowncoder** [comment]
@kbansod At this point I will need a Jackson-only reproduction (unit test) -- otherwise I can not help.
