### ISSUE TITLE
List in Map issue of version 2.10.2

### ISSUE THREAD

**Issue by jameshang** [FasterXML/jackson-dataformat-xml#394]
Example:

List<String> list=new ArrayList<>();
//put something into list
Map<String, List<String>> map=new HashMap<>();
map.put("abc", list);
//Then try to serialize map to xml and then try to deserialize xml back to the map object
//failed...

The xml structure is incorrect so that it cannot be deserialized back to object.

**Comment by cowtowncoder** [comment]
Root-level `Map`s and `List`s are not really supported: should use POJO.
