### ISSUE TITLE
Improve handling of "mixed content" with XML module

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-xml#402]
This is a placeholder issue for improving how Jackson handles XML content like:

```xml
<root>
   <value>123</value>
some text
   <value>345</value>
</root>
```

and other cases where a nesting level has both element(s) and at least one non-blank text value (content other than whitespace).

Currently such content can not be supported at all, and it is difficult to really find a general way of mapping this into POJOs.

However, it should be possible to have some level of support, for example maybe allow reading into `JsonNode` in some form -- considering that such text content could perhaps be mapped into empty key (and assuming handling of repeated Object keys can be resolved).
They may be other approaches too; to be discussed here.

**Comment by cowtowncoder** [comment]
Looks like `JsonNode` only detects mixed content that comes right after start element, but not one(s) after end-element.

**Comment by cowtowncoder** [comment]
Exposing of mixed content through `XmlTokenStream` (low-level) and `FromXmlParser` completed, which allowed fixing #405 so now mixed content is available via:

1. `JsonNode`, with logical key of `""` (empty String) -- and as per #403 value becomes `ArrayNode` if multiple mixed content found
2. "Untyped" case (`java.lang.Object`) as well: `Map` key of `""` (empty String), with either single `String` value or `List<String>` for multiple mixed content segments

Note that due to limitation in logic blank mixed content can not be included, so all-whitespace segments are not retained. This is unfortunately necessary to support use of indentation for non-mixed-content cases.

I will leave this issue open for possible future improvements regarding POJO (typed) use cases: these will not yet allow more than one `@XmlText` annotated segment.

**Comment by cRivault** [comment]
Could you please detail how is it supposed to be used with POJOs?

I have this problem in 1.11.2, tried your solution with the 1.12.0-snapshot, created a similar case with a root element containing a value field with @JacksonXMLText annotation.
I can confirm that trying to deserialize the element does not throw error anymore, but I can only get the raw text, but not any inner element ("some text" in your example). Am I missing something?

**Comment by cowtowncoder** [comment]
@Ace2Pic As things are, this would not help use with POJOs, unfortunately. It does help with `JsonNode` (which will retain duplicates) and, to a degree, "untyped" (read as `Object`) including case of binding into `Map`.

**Comment by Ace2Pic** [comment]
@cowtowncoder Thank you for your answer. It helped!
Using a simple custom deserializer and with `JsonNode `I am now able to get the whole "mixed content".

**Comment by cowtowncoder** [comment]
@Ace2Pic ah yes, that makes sense!

**Comment by nrodriguezmore** [comment]
> @cowtowncoder Thank you for your answer. It helped!
> Using a simple custom deserializer and with `JsonNode` I am now able to get the whole "mixed content".

can you share the custom deserializer you wrote? thanks!

**Comment by cowtowncoder** [comment]
Closing this due to following improvements that will be in 2.12:

* #205: when binding to `Object`, will now create `List`s for duplicate elements
* #403, #405: when binding to `JsonNode` will similarly create `ArrayNode` for duplicate.

Further improvements would be useful too but require specific ideas, and will likely need to go in 2.13 or later.
