### ISSUE TITLE
Migrate JAXB-referring tests to Jakarta EE 9

### ISSUE THREAD

**Issue by tamersaadeh** [FasterXML/jackson-dataformat-xml#408]
Jakarta EE 9 platform renames all the "old" namespaces from javax.xml.bind.* to jakarta.xml.bind.*. This pull request performs this migration so that when Jacakrta EE 9 is released in [June 2020](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan#proposed-progress-reviews) it will be compatible. Initial PR in #407.

**Comment by cowtowncoder** [comment]
Will most likely not proceed with this change until Jackson 3.0 (`master`); but even with it need to carefully orchestrate this as the change has high chance of breaking lots of users, use cases.

**Comment by cowtowncoder** [comment]
As per comments on PR, later changes for Jackson 2.13 allowed this to be done: simple change of annotations would not have worked (since Jackson's annotation introspector needed changes).

Thanks!
