### ISSUE TITLE
Cannot use @JacksonXmlText on a constructor property

### ISSUE THREAD

**Issue by raphw** [FasterXML/jackson-dataformat-xml#423]
Unfortunately, it is not possible to use `@JacksonXmlText` on a constructor what can be required in combination with `@JacksonXmlProperty(isAttribute = true)` what prevents one from creating immutable entities.

For example, the following object cannot be expressed using a constructor so that the immutable property needs to be emulated.

```
class Sample {
    @JacksonXmlText
    private String text;
    @JacksonXmlProperty(localName = "attribute", isAttribute = true)
    private String attribute;

    protected Sample () { }

    public Sample (String text, String attribute) {
        this.text = text;
        this.attribute = attribute;
    }
}
```

It would be nicer being able to use `@JacksonXmlText` on a constructor parameter.

**Comment by cowtowncoder** [comment]
@raphw That does sound like a limitation. So, just do make sure I understand: adding equivalent annotations on constructor parameters (and not on fields) would not work?

**Comment by raphw** [comment]
No, if I add the annotation to the field and let the constructor parameter blank, an exception is thrown.

**Comment by cowtowncoder** [comment]
@raphw ah. So while you can add `@JsonProperty`, that will mess handling ... I think there is a related issue, let me find it.

**Comment by cowtowncoder** [comment]
I think #306 might be related or maybe same? Problem, under the hood, is that "XmlText" is internally denoted as logical name of "", which unfortunately conflicts with 'missing name' option....

**Comment by cowtowncoder** [comment]
One quick note: #434 will allow use of `@JacksonXmlText` on (constructor) parameter. Likely it will not work, regardless, due to #306, but I will add a separate test for this case just to make sure.

**Comment by cowtowncoder** [comment]
Added a failing test along with #306; will close this as dup since I think it it the same underlying issue. Will close this issue, mark 306 as "most-wanted", hoping to address in 2.13 (or if lucky and doable in patch. 2.12.x).
