### ISSUE TITLE
Is jackson-dataformat-xml supported Primitive/Wrapper type as root element now?

### ISSUE THREAD

**Issue by HongZhaoHua** [FasterXML/jackson-dataformat-xml#424]
Is jackson-dataformat-xml supported Primitive/Wrapper type as root element now?

I write a test case like this:

```
        JacksonXmlModule module = new JacksonXmlModule();
        XmlMapper typeConverter = new XmlMapper(module);
        String content = typeConverter.writeValueAsString(new Date());
        typeConverter.readValue(content, Date.class);
```

but it will throws a Exception.

com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.Date` out of START_OBJECT token

**Comment by HongZhaoHua** [comment]
version is 2.10.0

**Comment by cowtowncoder** [comment]
Jackson 2.12.0 will finally support this, but unfortunately not earlier versions. 2.12.0 will hopefully be released within a month or so (or at least the first release candidate).

**Comment by HongZhaoHua** [comment]
Thank u very much.
