### ISSUE TITLE
xml with Character Entity failed to parse

### ISSUE THREAD

**Issue by taojoe** [FasterXML/jackson-dataformat-xml#429]
I've a problem with jackson, as following code, it cannot parse Character Entity.

&auml;( &amp;auml;) is a character entity.  which can be found [here](https://dev.w3.org/html5/html-author/charref)

```
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;

import java.io.IOException;

public class DynamicDataForXml {
    public static void main(String[] args) throws IOException {
        String xml= "<a>aa&amp;auml;</a>";
        XmlMapper xmlMapper = new XmlMapper();
        JsonNode node = xmlMapper.readTree(xml.getBytes());
        ObjectMapper mapper = new ObjectMapper();
        String json = mapper.writeValueAsString(node);
        System.out.println(json);
    }
}
```

throw exception :
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Undeclared general entity "auml"

now i'm use the 2.12.0-rc1 version.

**Comment by cowtowncoder** [comment]
This is invalid XML: entities must be declared in DTDs, except for 4 pre-declared ones (gt, lt, apos, quot).
`&auml;` is not one of these. Based on what you link to, I think you will need to find html5 dtd, add reference to it from `<!DOCTYPE` declaration.

**Comment by taojoe** [comment]
hi @cowtowncoder ,

according to the following answer, there is no html5 dtd. So is there any example code to solve this? 

https://stackoverflow.com/questions/4053917/where-is-the-html5-document-type-definition

**Comment by cowtowncoder** [comment]
This is question on standard XML handling so I hope you can find it: searching for "dtd general entities", you find f.ex:

https://www.tutorialspoint.com/dtd/dtd_entities.htm

and you can either use embedded DTD subset (definitions in xml document), or reference to external resource.

But if your XML content does not have DTD declarations then that is invalid and whoever created it is not a valid XML document at all but broken thing. Whoever wrote that should fix it.
