### ISSUE TITLE
XmlTokenStream does not respect FromXmlParser.Feature.EMPTY_ELEMENT_AS_NULL in 2.11

### ISSUE THREAD

**Issue by nhalase** [FasterXML/jackson-dataformat-xml#438]
When deserializing the following XML, I would expect `<Element2>` to yield a `null` value in my POJO.

```xml
<MyObject proprietary-type="Array">
    <Element1 proprietary-length="1" proprietary-type="String">Y</Element1>
    <Element2 proprietary-length="2" proprietary-type="String"/>
    <Element3 proprietary-length="1" proprietary-type="String">1</Element3>
    <Element4 proprietary-length="2" proprietary-type="String">1</Element4>
</MyObject>
```

Given the following XML, I receive the results I'm expecting:

```xml
<MyObject proprietary-type="Array">
    <Element1 proprietary-length="1" proprietary-type="String">Y</Element1>
    <Element2/>
    <Element3 proprietary-length="1" proprietary-type="String">1</Element3>
    <Element4 proprietary-length="2" proprietary-type="String">1</Element4>
</MyObject>
```

It looks like this is due to #167 via [this code](https://github.com/FasterXML/jackson-dataformat-xml/blob/031aa5e10325929e16e24e2192a76442196fe74c/src/main/java/com/fasterxml/jackson/dataformat/xml/deser/XmlTokenStream.java#L319-L325), but I could be missing something. I would expect the linked code to perform a check for FromXmlParser.Feature.EMPTY_ELEMENT_AS_NULL rather than hard-default to empty String.

For context, I have no control over the XML I'm receiving and trying to deserialize—it's third-party.

**Comment by cowtowncoder** [comment]
Since 2.12.0 is now released, I am curious if this still happens?

**Comment by cowtowncoder** [comment]
Would need a reproduction; may be reopened with a test that includes POJO definitions, code to reproduce the problem.
