### ISSUE TITLE
XmlBeanSerializer doesn't implement serializeFieldsFiltered

### ISSUE THREAD

**Issue by lalmeras** [FasterXML/jackson-dataformat-xml#44]
XmlBeanSerializer doesn't implement serializeFieldsFiltered so that custom XML annotations (like @JacksonXmlProperty(isAttribute = ...) are not used if a filter is defined on the serialized POJO.

**Comment by amolfuke** [comment]
Hi ,
I am still having this issue mentioned by @lalmeras and I am using latest fasterxml libs (version 2.7.x).Any idea whats wrong ?

            /*****/
            XmlMapper mapper = new XmlMapper();

            SimpleFilterProvider filters = new SimpleFilterProvider();
            filters.addFilter("campaignBeanFilter",SimpleBeanPropertyFilter.filterOutAllExcept("name","id","site"));
           
            mapper.setFilters(filters);
  
            return mapper.writeValueAsString(campaignBean);
			/*****/

**Comment by cowtowncoder** [comment]
@amolfuke could you please file a new issue, adding a brief reference to this as possibly related? Also, reproducible use case would be useful; your sample code in itself is not enough to show problem you have.
