### ISSUE TITLE
@XmlElementRef ignores @XmlRootElement names; @XmlElementRefs use wraps with collection field name

### ISSUE THREAD

**Issue by wjjanning** [FasterXML/jackson-dataformat-xml#440]
Java8, Jackson-data-format 2.11.3
Using @XmlElementRef on a List for polymorphic class elements does not use name from @XmlRootElement. In the code below:

        @XmlElementRef(name="")
        List<Task> tasks = new ArrayList<>();

Produces output of:

![image](https://user-images.githubusercontent.com/52182832/101735774-ff1cb700-3a87-11eb-92a4-aea55b53f3f8.png)

Which is good (no wrappers) but the word "tasks" should be "jar" and "javac" respectively per the actual subclass used.

If @XmlElementRefs is used then the elements names are correct, but now wrapped in a "tasks" element which is undesirable. This solution is undesirable in that all the possible subclasses must be listed here.

        @XmlElementRefs({
		@XmlElementRef(type = JarTask.class),
		@XmlElementRef(type = JavacTask.class)
        })
        List<Task> tasks = new ArrayList<>();

Output:

![image](https://user-images.githubusercontent.com/52182832/101735870-24a9c080-3a88-11eb-8d77-67b07950f5b1.png)

Use of @XmlElementRef should be getting the element name from the XmlRootElement annotation or worse case the actual subclass name. 

--- code ---

```java
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonGenerationException;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator;
import com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule;

@XmlRootElement(name="target")
public class Target {
    // The presence of @XmlElementRef indicates that the XML
    // element name will be derived from the @XmlRootElement
    // annotation on the type (for e.g. "jar" for JarTask).
	//@XmlElementRefs({
	//	@XmlElementRef(type = JarTask.class),
	//	@XmlElementRef(type = JavacTask.class)
	//})
	@XmlElementRef()
    List<Task> tasks = new ArrayList<>();
    
    public List<Task> getTasks() {
		return tasks;
	}

	public void setTasks(List<Task> tasks) {
		this.tasks = tasks;
	}

	public static void main(String[] args) {
    	XmlMapper xmlMapper = new XmlMapper();
    	xmlMapper.registerModule(new JaxbAnnotationModule());
    	xmlMapper.configure(ToXmlGenerator.Feature.WRITE_XML_DECLARATION, true);
    	xmlMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    	xmlMapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);
    	xmlMapper.configure(SerializationFeature.WRAP_ROOT_VALUE, false);
    	xmlMapper.configure(SerializationFeature.WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED, true);
    	xmlMapper.setDefaultUseWrapper(false);
    	
    	Target target = new Target();
        target.tasks.add(new JarTask().filename("somefile.jar"));
        target.tasks.add(new JavacTask().filepath("/home/myapp/target").libpath("/usr/lib"));

    	try {
    		xmlMapper.writeValue(System.out, target);
    	}
    	catch (JsonGenerationException e) {
    		e.printStackTrace();
    	}
    	catch (JsonMappingException e) {
    		e.printStackTrace();
    	}
    	catch (IOException e) {
    		e.printStackTrace();
    	}
    }        
}

abstract class Task {
}

@XmlRootElement(name="jar")
@XmlAccessorType(XmlAccessType.FIELD)
class JarTask extends Task {
	@XmlAttribute(name = "file", required = true)
	private String filename;

	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}
	
	public JarTask filename(String filename) {
		this.filename = filename;
		return this;
	}
}

@XmlRootElement(name="javac")
@XmlAccessorType(XmlAccessType.FIELD)
class JavacTask extends Task {
	@XmlAttribute(name = "path", required = true)
	private String filepath;
	
	@XmlAttribute(name = "lib")
	private String libpath;

	public String getFilepath() {
		return filepath;
	}

	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	public JavacTask filepath(String filepath) {
		this.filepath = filepath;
		return this;
	}

	public String getLibpath() {
		return libpath;
	}

	public void setLibpath(String libpath) {
		this.libpath = libpath;
	}
	
	public JavacTask libpath(String libpath) {
		this.libpath = libpath;
		return this;
	}
}
```

**Comment by cowtowncoder** [comment]
Jackson is not a JAXB implementation and although there is JAXB annotation support, not all semantics are carried.
`XmlElementRefs` is explicitly mentioned as not supported by `JaxbAnnotationsModule`, although aspect of subtype linkage is used. It has no effect on naming or inclusion of type information, however.

Put another way: only those aspects that can be controlled by native Jackson annotations are controlled by JAXB annotations. Root element name is never used by Jackson for anything other than root element.

**Comment by wjjanning** [comment]
Sorry to see there will be no fix for this deficiency. If you have subtype linkage then how difficult is it to process the root name for the subtype? The fact that native Jackson annotations cannot do this behavior either means that the whole Jackson XML support is really not ready for prime time. :(

**Comment by cowtowncoder** [comment]
@wjjanning I am not sure why you expect for Jackson to implement all concepts of JAXB: Jackson neither is nor never claimed to implement JAXB. While there is optional compatibility support for many of JAXB _annotations_, processing models are different.

As to root name, as name implies, that is only needed for root value. Why JAXB defines that to be used for some secondary uses I do not know.

Reference to Jackson annotations (general-purpose, as well as XML-specific ones of this project) are meant to give an approximation what to expect.
