### ISSUE TITLE
Missing `START_OBJECT` token in complex element starting with text

### ISSUE THREAD

**Issue by richardsonwk** [FasterXML/jackson-dataformat-xml#442]
In version 2.12.0, I think XmlTokenStream might be omitting START_OBJECT tokens when a complex element starts with text content. The following has two START_OBJECT tokens but three END_OBJECT tokens:

```
        final String example = String.join("\n", Arrays.asList(
            "<SomeXml>", // START_OBJECT
            "  <ParentElement>", // *Missing* START_OBJECT
            "     text",
            "     <ChildElement someAttribute=\"value\"/>", // START_OBJECT/END_OBJECT
            "     further text",
            "  </ParentElement>", // END_OBJECT
            "</SomeXml>")); // END_OBJECT

        final XmlFactory factory = new XmlFactory();
        final JsonParser parser = factory.createParser(example);

        while (parser.nextToken() != null) {
            System.out.println(parser.currentToken()
                + (parser.getValueAsString() != null ? "(" + parser.getValueAsString() + ")" : ""));
        }
```

The output is 

```
START_OBJECT
FIELD_NAME(ParentElement)
FIELD_NAME()
VALUE_STRING(
     text
     )
FIELD_NAME(ChildElement)
START_OBJECT
FIELD_NAME(someAttribute)
VALUE_STRING(value)
END_OBJECT
FIELD_NAME()
VALUE_STRING(
     further text
  )
END_OBJECT
END_OBJECT
```

Maybe there's a point of configuration I'm missing?

**Comment by cowtowncoder** [comment]
It does sound like potential flaw in token stream, yes, probably related to 2.12 change to expose mixed content (see #405). There is no configurability of underlying stream so ideally this could be fixed without breaking any existing functionality.

**Comment by cowtowncoder** [comment]
Finally had a good solid reason to have to fix this: recent un-recursing of `JsonNode` deserialization made this a necessity (in the past that handled "orphan FIELD_NAME" case by implicit assumption of leading START_OBJECT; not any longer)
