### ISSUE TITLE
XML reading with getting null back

### ISSUE THREAD

**Issue by RealMarvn** [FasterXML/jackson-dataformat-xml#457]
Hey Guys, 
I cant find any support Discord or other good support ways to chat with you. First at all! I need to read that one XML format i`ll get sent from Google (String). So I am parsing it to your XML mapper.
![image](https://user-images.githubusercontent.com/67916561/111551864-777ace80-8781-11eb-9785-5b2014d926ec.png)

As you Guys can see on my Image below this Message I tried to use you JacksonXmlProperty to get the values which are in that XML multiple times. I am not familiar with XML so pls do not defend me because of my knowlage.
![image](https://user-images.githubusercontent.com/67916561/111552095-ece69f00-8781-11eb-8ae3-9a2f2d9fad0e.png)

I am using Lombok for a Getter! I also printed out every value on this and the only value which is not null everytime is title (which is one of the multiple but it is the wrong one). Can you Guys help me getting these null problems fixed and make the lib finding the right values for me? 

This is btw the XML format I`ll get so you guys know what values i tried to get.
![image](https://user-images.githubusercontent.com/67916561/111552325-58c90780-8782-11eb-8586-3a75b15adcef.png)

Pls help me I am really frustrated because I am not that familier with

Best Regards Marvn

**Comment by cowtowncoder** [comment]
Ok, there is a chat at:

https://gitter.im/FasterXML/jackson-databind

where you might get help.

Otherwise what I suggest you to do is to first create Java object (POJO), and then serialize that with

    String xml = mapper.writeValueAsString(myObject);

to see how structure differs. It is likely there is some difference.

**Comment by RealMarvn** [comment]
Ah ok thx. I used that XmlMapper.writeValuesString and I got this out:


<String>&lt;?xml version='1.0' encoding='UTF-8'?>
&lt;feed xmlns:yt="http://www.youtube.com/xml/schemas/2015" xmlns="http://www.w3.org/2005/Atom">&lt;link rel="hub" href="https://pubsubhubbub.appspot.com"/>&lt;link rel="self" href="https://www.youtube.com/xml/feeds/videos.xml?channel_id=UCMGkGVQWdicquiCycfhg4lw"/>&lt;title>YouTube video feed&lt;/title>&lt;updated>2021-03-18T09:01:23.226542817+00:00&lt;/updated>&lt;entry>
  &lt;id>yt:video:BzkvTOQO6CM&lt;/id>
  &lt;yt:videoId>BzkvTOQO6CM&lt;/yt:videoId>
  &lt;yt:channelId>UCMGkGVQWdicquiCycfhg4lw&lt;/yt:channelId>
  &lt;title>Programming Test&lt;/title>
  &lt;link rel="alternate" href="https://www.youtube.com/watch?v=BzkvTOQO6CM"/>
  &lt;author>
   &lt;name>Mohammed&lt;/name>
   &lt;uri>https://www.youtube.com/channel/UCMGkGVQWdicquiCycfhg4lw&lt;/uri>
  &lt;/author>
  &lt;published>2021-03-18T09:00:43+00:00&lt;/published>
  &lt;updated>2021-03-18T09:01:23.226542817+00:00&lt;/updated>
 &lt;/entry>&lt;/feed>
</String>


This is way different that the normal....But what did that exaclty change for my null problem?

**Comment by cowtowncoder** [comment]
@RealMarvn the structure has to match: otherwise values you expect will not be bound to values you expect.
`null` typically just means "no value seen for this property".

But one thing to check first that I should have mentioned is to make sure to use a recent version of `jackson-dataformat-xml`, 2.12.2.
It had A LOT of fixes over 2.11 and earlier version.

**Comment by cowtowncoder** [comment]
Not sure what exactly the issue is supposed to be without unit test: may be reopened with a reproduction (unit test).
