### ISSUE TITLE
OSS-Fuzz integration

### ISSUE THREAD

**Issue by fmeum** [FasterXML/jackson-dataformat-xml#461]
I have finalized the OSS-Fuzz integration for the XML parser at https://github.com/google/oss-fuzz/pull/5551 and will submit a PR for the status badge once it has been merged.

**Comment by cowtowncoder** [comment]
Excellent! Looking forward to interesting findings here too. :)

**Comment by cowtowncoder** [comment]
First issue already found. Closing this.
