### ISSUE TITLE
Weird unexpected error in already working code com.fasterxml.jackson.databind.exc.MismatchedInputException

### ISSUE THREAD

**Issue by vmisra2018** [FasterXML/jackson-dataformat-xml#466]
.
I am getting weird error 
 ```
 com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name 'status' does not match expected ('JsonNode') for type [simple type, class com.fasterxml.jackson.databind.JsonNode]
 at [Source: (String)"{"status":"some message"}"; line: 1, column: 2] 
 ```
in already working code.In our spring legacy code (not boot) , the change I did was to add jackson-dataformat-xml dependency [core and annotation were already there] . I required it for xml support.  I have :
  ${jackson.version}= 2.10.0
 
 ```
 <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
           <groupId>com.fasterxml.jackson.core</groupId>
           <artifactId>jackson-annotations</artifactId>
           <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <artifactId>jackson-dataformat-xml</artifactId>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <version>${jackson.version}</version>
        </dependency>
```
But suddenly old code started to give above error . And I have to  replace readTree with ObjectReader readerFor.
For  a  sample response from  external service which is as simple as 
``` {"payload":"09e1cbef059f4bf8b15269cc340b838e"}
 ```
   Why do I have to suddenly change from readTree to like below :
 
``` 
       try {
               ...
                 //JsonNode rootNode = objectMapper.readTree(resultInJson);
                  ObjectReader reader = objectMapper.readerFor(JsonNode.class).withoutRootName();
                  JsonNode rootNode = reader.readValue(resultInJson);
                  
              } catch (JsonProcessingException e) {
                  LOGGER.warn(e, e);
              }
        
```

Objectmapper is being used in lits of places . So I am worried as to why I have to change existing code?
  Update:
   I found out the reason for this error. I have an incoming xml in one API and I am using  jackson-dataformat-xml to convert it to JSON and object.  The format of xml and mapped obj is below :
       ```xml
               <messageroot>
                   <message> fields go here
                   </message>
              </messageroot>
     ```
Java mapping:
  ```
                @Configurable(dependencyCheck = true)
                 @JsonRootName(value = "message")
                  public class GenericMessage {
                  //fields
                 }
    
    
```   
         I have to add this line :
```  
        objectMapper.configure(DeserializationFeature.UNWRAP_ROOT_VALUE, true);
```
else it throws com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException and adding @JsonIgnoreProperties(ignoreUnknown = true) has no effect and objects comes as null But when i add above, I get  mentoned MismatchedInputException later in other places  where other api are trying to use mapper to get JsonNode
So What I did was  turned the flag to false once I got the object from XML  ,see below : 
```     
                    public Object xmlToObject(String xml, Class clazz) {
                          String json = "";
                          JsonNode jsonRootNode = null;
                          Object deserialedObject = null;
                          try {
                              jsonRootNode = xmlMapper.readTree(xml.getBytes());
                              ObjectMapper objectMapper = objectMapperFactory.getObjectMapper();
                              objectMapper.configure(DeserializationFeature.UNWRAP_ROOT_VALUE, true);
                              json = objectMapper.writeValueAsString(jsonRootNode);
                              deserialedObject = objectMapper.readValue(json, clazz);
                              objectMapper.configure(DeserializationFeature.UNWRAP_ROOT_VALUE, false);//ADDED THIS
                          } catch (IOException e) {
                              LOGGER.error(e.getMessage());
                          }
                          return deserialedObject;
                      }
 ```     
 This fixed the error. And I no longer have to use ObjectReader and .withoutRootName() in other places. But I am not sure if this is correct approach.
  I  also tried to ignore root like below  to process incoming xml:
 ```   
                   public Object xmlToObject(String xml, Class clazz) {
        String json = "";
        JsonNode jsonRootNode = null;
        Object deserialedObject = null;
        try {
            jsonRootNode = xmlMapper.readTree(xml.getBytes());
            ObjectMapper objectMapper = objectMapperFactory.getObjectMapper();
            json = objectMapper.writer().withoutRootName().writeValueAsString(jsonRootNode);
            deserialedObject = objectMapper.readValue(json, clazz);
        } catch (IOException e) {
            LOGGER.error(e.getMessage());
        }
        return deserialedObject;
    }
```  
But then again I got : 
```  
      - Unrecognized field "message" (class x.y.z.GenericMessage), not marked as ignorable (14 known properties: ".."])
```

**Comment by cowtowncoder** [comment]
At this point knowing the timeline of your application and former Spring support does not really help understand the problem (beyond your saying that behavior is different).
Main question to me, with respect to 2.12, is whether the observed behavior at this point is as expected on its own.

One thing to note is that use of tree model (`JsonNode`) was specifically NOT supported with XML at all before Jackson 2.12. This was mentioned on README as a limitation. It did not work well, especially with repeated elements.
It is unfortunate if you relied on it for production code.

With that, if you can express the problem in stand-alone unit test, that would be helpful: with specified content, Java Object(s), XML, what is expected outcome?
(Jackson tries to guarantee invariant that it can read any XML content it writes: but there are types of XML content it cannot necessarily read)

**Comment by vmisra2018** [comment]
I think i was messing around with Jackson json objectmapper unnecessarily . All I needed was for one api to serialize xmls coming as java object with parent tag of xml("messageroot") stripped. So I made this change and now it will not affect json objectmapper config.

```
      public Object xmlToObject(String xml, Class clazz) {
        Object deserialedObject = null;
        try {
            xmlMapper.configure(DeserializationFeature.UNWRAP_ROOT_VALUE, true);
            deserialedObject = xmlMapper.reader().forType(clazz).readValue(xml.getBytes());
           
        } catch (IOException e) {
            LOGGER.error(e.getMessage());
        }
        return deserialedObject;
    }

```
I have now in Object 
```
     @Configurable(dependencyCheck = true)
      @JsonRootName(value = "message")
      @JacksonXmlRootElement(localName = "message")
       public class GenericMessage {
           //fields
       }
```
I will also upgrade version and I am not using readTree. If this is OK , then I will close the issue .

**Comment by cowtowncoder** [comment]
@vmisra2018 Yes, that seems like the correct approach if you have "wrapping" in JSON content. There are couple of different ways to enable that unwrapping; `ObjectReader` also has method `withRootName()` to enable unwrapping with specific name to match.

**Comment by vmisra2018** [comment]
Thanks @cowtowncoder . I am closing the issue.
