### ISSUE TITLE
Parsing of null String fields changed behavior between version 2.11.4 and 2.12.x and newer

### ISSUE THREAD

**Issue by Crim** [FasterXML/jackson-dataformat-xml#507]
Almost the same as #473 , apologies for not catching the changed behavior of strings at the same time as posting that issue.

Running version `2.11.4` using the following configuration:

```java
        // Create new mapper
        final JacksonXmlModule module = new JacksonXmlModule();
        module.setDefaultUseWrapper(false);

        final XmlMapper mapper = new XmlMapper(module);

        // Configure it
        mapper
            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
            .setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE)
            .registerModule(new JodaModule())
            .setDateFormat(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"));
```

Parsing the following xml:

```xml
        <campaign>
            <id>123</id>
            <name/>
        </campaign>
```

into the following bean:
```java
public class Campaign {
    private Long id;
    private String name;

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setName(final String name) {
        this.name = name;
    }
}
```

usage:
```
  // mapper instance as defined above, campaignXmlStr as defined above.
  mapper.readValue(campaignXmlStr, Campaign.class);
```

The above JSON gets deserialized into the bean with the `name` property being set to `null`.

With version `2.12.x` and newer the `name` property becomes `""` (empty string)

Is this considered a bug? Or expected behavior for newer versions?  Is there a way to revert to the previous behavior via config?

Thanks!

**Comment by cowtowncoder** [comment]
There is setting

    FromXmlParser.EMPTY_ELEMENT_AS_NULL

which may be relevant here. But other than that the new behavior is considered correct for `String` values: there really is no good way to indicate `null` in XML except by using `xsi:nil="true"` marker.
That marker is processed if `FromXmlParser.PROCESS_XSI_NIL` is `true` (which is the default setting).

**Comment by Crim** [comment]
Awesome, that worked perfectly.  Thanks for sorting me out!
