### ISSUE TITLE
Prefixed element is not supported

### ISSUE THREAD

**Issue by mincong-h** [FasterXML/jackson-dataformat-xml#515]
Currently if there are two elements with the same name, one with prefix and the other without prefix, Jackson XML mapper cannot read them correctly. For example, in the following structure, mapper fails to recognize the "media:content" properly:

```xml
<post>
  <content>&lt;p&gt;Hello world!&lt;/p&gt;</content>
  <media:content medium="image" url="http://example.com" xmlns:media="http://search.yahoo.com/mrss/" />
</post>
```

I discovered this when trying to read the feed (RSS) of my blog (<https://mincong.io/feed.xml>). The XML structure is generated by Jekyll Feed plugin ([source code](https://github.com/jekyll/jekyll-feed/blob/9c27cf60fe1f45ef74f95d1e972dc0856a7cbe30/lib/jekyll-feed/feed.xml#L108)), where both `content` and `media:content` exist, so I don't want to modify them if possible. I am using Jackson XML in version 2.13.2.

Here is the test suite to reproduce the problem, where the 2nd test fails with content as empty string:

```java
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class PrefixedElementTest {

    @JacksonXmlRootElement(localName = "post")
    static class MyPost {
        @JacksonXmlProperty(localName = "content")
        String content;
    }

    @Test
    void withoutMediaContent() throws Exception {
        var mapper = new XmlMapper();
        var post = mapper.readValue("""
        <post>
            <content>&lt;p&gt;Hello world!&lt;/p&gt;</content>
        </post>
        """, MyPost.class);
        assertThat(post.content).isEqualTo("<p>Hello world!</p>");
    }

    @Test
    void withMediaContent() throws Exception {
        var mapper = new XmlMapper();
        var post = mapper.readValue("""
        <post>
            <content>&lt;p&gt;Hello world!&lt;/p&gt;</content>
            <media:content medium="image" url="http://example.com" xmlns:media="http://search.yahoo.com/mrss/" />
        </post>
        """, MyPost.class);

        // org.opentest4j.AssertionFailedError: 
        // Expecting:
        // <"">
        // to be equal to:
        // <"<p>Hello world!</p>">
        // but was not.
        assertThat(post.content).isEqualTo("<p>Hello world!</p>");
    }
}
```

**Comment by cowtowncoder** [comment]
Correct: Jackson XML module does not allow elements or attributes that only differ by namespace (prefixes map to namespaces in XML).
This is a limitation that exists currently and there are no current plans to change this behavior -- theoretically it could be fixed, of course, as Jackson does keep track of declared namespace. But only local name is currently used for matching properties.

**Comment by mincong-h** [comment]
Thanks for your quick reply @cowtowncoder , really appreciate that. Your explanation is very clear. 👍 By the way, I ended up using [jsoup](https://github.com/jhy/jsoup) as the replacement and relies on CSS selector to find the right tag (`content` or `media:content`).

**Comment by cowtowncoder** [comment]
@mincong-h thank you -- and apologies for having to go through the workaround. Ideally it really should "just work". But I am glad you were able to find a workaround.
