### ISSUE TITLE
EMPTY_ELEMENT_AS_NULL should also work when there is an opening and closing tag with no content

### ISSUE THREAD

**Issue by tkvangorder** [FasterXML/jackson-dataformat-xml#516]
First off, thank you for the amazing library, seriously. 

Version: jackson-dataformat-xml:2.13.2

Encountered an interesting edge case when using `FromXmlParser.EMPTY_ELEMENT_AS_NULL`:

For context, we have a model object: 

```
import lombok.AccessLevel;
import lombok.Data;
import lombok.experimental.FieldDefaults;
import org.openrewrite.internal.lang.Nullable;

@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Data
public class ProfileActivation {
    @Nullable
    Boolean activeByDefault;

    @Nullable
    String jdk;

    @Nullable
    Property property;
}
```

[And in the XmlMapper.Builder we are enabling `FromXmlParser.Feature.EMPTY_ELEMENT_AS_NULL`.](https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenXmlMapper.java#L51)

This is working correctly when the XML string includes an empty tag.

```
                    <project>
                        <groupId>org.openrewrite.maven</groupId>
                        <artifactId>test</artifactId>
                        <version>0.1.0-SNAPSHOT</version>
                        <profiles>
                            <profile>
                              <id>repo-incode-work</id>
                              <activation/>
                            </profile>
                        </profiles>
                    </project>
```

But is not working if activation has opening/closing tags:

```
                    <project>
                        <groupId>org.openrewrite.maven</groupId>
                        <artifactId>test</artifactId>
                        <version>0.1.0-SNAPSHOT</version>
                        <profiles>
                            <profile>
                              <id>repo-incode-work</id>
                              <activation></activation>
                            </profile>
                        </profiles>
                    </project>
```

We have worked around this problem by allowing an empty model object to be created, but it is strange that one situation leads to a null profile and another leads to an instance with all null fields. 

For context: 

https://github.com/openrewrite/rewrite/issues/1487

[These are the tests we have.](https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/test/kotlin/org/openrewrite/maven/MavenParserTest.kt#L836-L894)

**Comment by cowtowncoder** [comment]
Thank you!

The case of empty String vs `null` is a tough one, conceptually. Over time it has become clear that it is not really possible to tell the cases apart without some additional metadata, so newer versions tend to just produce empty String for most cases.

Now, as to `EMPTY_ELEMENT_AS_NULL`, Javadocs specifically state that it only applies to tags like

```
<tag />
```

and NOT to logically equivalent (in XML infoset)

```
<tag></tag>
```

case:

```
        /**
         * Feature that indicates whether XML Empty elements (ones where there are
         * no separate start and end tags, but just one tag that ends with "/&gt;")
         * are exposed as {@link JsonToken#VALUE_NULL}) or not. If they are not
         * returned as `null` tokens, they will be returned as {@link JsonToken#VALUE_STRING}
         * tokens with textual value of "" (empty String).
         *<p>
         * Default setting was {@code true} (for backwards compatibility from 2.9 to 2.11 (inclusive)
         * but was changed in 2.12 to be {@code false} (see [dataformat-xml#411] for details)
         *
         * @since 2.9
         */
        EMPTY_ELEMENT_AS_NULL(false),
```

so in that sense behavior is as documented.

This is not necessarily ideal behavior but at this point it is unlikely we can change it as some users may rely on its semantics.

Given this, the best thing to do is probably to actually disable this setting and either:

* Check for empty String in your code, always (no `null`s should be produced)
* Add/override setter to coerce empty String to `null` on the fly.

**Comment by tkvangorder** [comment]
OK, I understand not wanting to break others, we have worked around the problem by allowing an empty activation model object with we encounter opening and closing tags. Thanks for the explaination.
