### ISSUE TITLE
Spring 5 -jackson-dataformat-xml forces @ResponseBody with XML

### ISSUE THREAD

**Issue by ztcarrot** [FasterXML/jackson-dataformat-xml#529]
our api response default content type is changed to XML unexpectedly when I add below dependency in pom.xml, it should be application/json. and I don't know it will change it. could you please fix this issue? Thanks

```
<dependency>
	<groupId>com.fasterxml.jackson.dataformat</groupId>
	<artifactId>jackson-dataformat-xml</artifactId>
	<version>2.12.2</version>
</dependency>
```

**Comment by cowtowncoder** [comment]
Jackson cannot change the content type on its own so something else changing it.
I suggest you try a Spring user forum maybe they can help you.

Or if you want to reach out to users of Jackson, mailing list would be:

https://groups.google.com/g/jackson-user

However, issue tracker is not a good way to ask usage questions like this.
