### ISSUE TITLE
jackson-dataformat-xml changed the default response content type from 'application/json' to 'application/xml'

### ISSUE THREAD

**Issue by VampireDaniel** [FasterXML/jackson-dataformat-xml#530]
Hello project maintainer

This is a really good module and helps us a lot in our java application, which some API need to response with XML

But during the integration with this module in our java spring boot application, some APIs response content type got unexpected changed from 'application/json' to 'application/xml' when no indication in HTTP content. before added this module everything would be returned in JSON, and everything works fine and well.

So after some research, seems some people have same issue as well,
https://stackoverflow.com/questions/41036377/spring-mvc-changing-default-response-format-from-xml-to-json
https://stackoverflow.com/questions/66752245/spring-5-jackson-dataformat-xml-forces-responsebody-with-xml
https://stackoverflow.com/questions/57706610/how-to-set-default-messageconverter-to-json-with-jackson-dataformat-xml-added

The issue is easy to resolve, either to ask the client to indicate the Accept in header or add a limitation in Java service side, both work. 
But the reason still want to raise an issue here is to purpose, can the project maintainer add maybe one Warning Section/Headsup Section on the Readme page to let all of the developers know, there might have one potential check on API response after leveraging this module.

Thanks a lot.

**Comment by cowtowncoder** [comment]
Why do you think this module does anything? It literally does absolutely nothing to Spring: Spring uses this module, not the other way around.

So please ask on Spring users lists or support forums: `jackson-dataformat-xml` knows absolutely nothing about anything Spring framework does.

I would be happy to add some verbiage on READMEs -- ideally links to something that explains the issue -- once this is understood. But at this point it is not clear to me what specifically happens. I can only speculate that Spring has auto-detection of Jackson modules and thereby does something that changes some behavior.
But this really has everything to do with Spring; so this part needs to be understood.

**Comment by VampireDaniel** [comment]
@cowtowncoder  Thanks a lot

**Comment by oleksandrzakharov** [comment]
You can use in spring spring.xml.ignore=true
