### ISSUE TITLE
how to keep attribute order?

### ISSUE THREAD

**Issue by yidou120** [FasterXML/jackson-dataformat-xml#553]
I use @JsonOrder，but attribute that use attribute is true cannot order correctly. this annotation only useful for property field.

**Comment by cowtowncoder** [comment]
Attributes should be output in specific order according to `@JsonPropertyOrder`, although in XML attribute order has no semantic meaning.
Do you have an example case showing different ordering?

**Comment by yidou120** [comment]
this is pojo defined.
```
@JacksonXmlRootElement(localName = "person")
@Data
public class Person {
    @JacksonXmlProperty(isAttribute = true)
    private String email;
    @JacksonXmlProperty(isAttribute = true, localName = "person_name")
    private String name;
    @JacksonXmlProperty(isAttribute = true)
    private int age;

    private Adress adress;
    @JacksonXmlElementWrapper(useWrapping = false)
    @JacksonXmlProperty(localName = "friend")
    private List<Friend> friendList;
}
this is output.
```
<?xml version='1.0' encoding='UTF-8'?>
<person email="123@qq.com" age="10" person_name="attribute name">
  <adress>
    <province>lanzhou</province>
    <code>188</code>
  </adress>
  <friend>
    <name>test1</name>
    <age>10</age>
  </friend>
  <friend>
    <name>test2</name>
    <age>101</age>
  </friend>
</person>
``
I expect person_name attribute is before age. because pojo order is that.

**Comment by yidou120** [comment]
this is output.

<?xml version='1.0' encoding='UTF-8'?>
<person email="123@qq.com" age="10" person_name="attribute name">
  <adress>
    <province>lanzhou</province>
    <code>188</code>
  </adress>
  <friend>
    <name>test1</name>
    <age>10</age>
  </friend>
  <friend>
    <name>test2</name>
    <age>101</age>
  </friend>
</person>

I expect person_name attribute is before age. because pojo order is that.

**Comment by yidou120** [comment]
I use @JsonPropertyOrder(value = {"email, name, age"}) this annotation, it seems not useful.

**Comment by cowtowncoder** [comment]
Maybe try using `person_name` instead of `age` for the annotation? (both should work, ideally, but maybe there's something preventing use of original name before renaming).

And yes, `@JsonPropertyOrder` should work.

One thing to make sure is that Lombok (since that is used I think?) does not remove any annotations on generated classes.

**Comment by yidou120** [comment]
yes, I tried to use person_name instead of name, but order still wrong.
and lombok does not remove any annotations on generated classes.
![image](https://user-images.githubusercontent.com/22814269/200452440-ec2af0fb-8b8c-43d3-8a21-bb78ce9bc0f2.png)

**Comment by cowtowncoder** [comment]
@yidou120 Your problem is here:

```
I use 

@JsonPropertyOrder(value = {"email, name, age"})

this annotation, it seems not useful.
```

where you accidentally have single String, instead of 3 Strings like so:

```
@JsonPropertyOrder(value = {"email", "name", "age"})
```
