### ISSUE TITLE
Add `DefaultXmlPrettyPrinter.withCustomNewLine()` to configure linefeed for XML pretty-printing

### ISSUE THREAD

**Issue by koalalam** [FasterXML/jackson-dataformat-xml#560]
Jackson version: 2.14.1

In `ObjectMapper` case, we can do the following:

```java
objectMapper.setDefaultPrettyPrinter(new DefaultPrettyPrinter().withObjectIndenter(new DefaultIndenter().withLinefeed("\n")));
```

However in `XmlMapper`. the default implementation [Lf2SpacesIndenter](https://github.com/FasterXML/jackson-dataformat-xml/blob/jackson-dataformat-xml-2.14.1/src/main/java/com/fasterxml/jackson/dataformat/xml/util/DefaultXmlPrettyPrinter.java#L504)
1) Is protected
2) Doesn't seem to support a custom line separator

Does it mean we need to provide our own implementation of `Indenter` just to have a different line separator?

**Comment by cowtowncoder** [comment]
Seems like an oversight, thank you for reporting it.

If you have time and interest, a PR would make sense, if you end up trying writing a custom implementation anyway.
