### ISSUE TITLE
support StreamReadContraints maxStringSize

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-dataformat-xml#571]
* FromXmlParser does not use TextBuffer to build up text so it does not benefit from the jackson-core support for ReadConstrainedTextBuffer
* there are probably a few ways that support could be added to FromXmlParser

**Comment by cowtowncoder** [comment]
Yeah. FWTW, Woodstox does have limits via:

https://cowtowncoder.medium.com/configuring-woodstox-xml-parser-woodstox-specific-properties-1ce5030a5173

including `P_MAX_TEXT_LENGTH`, but integrating that would be tricky.

So one possibility would be documentation.

In theory it'd be possible to -- with quite a bit of work -- change handling to avoid automatic text coalescing, which would usually make Stax implementation return text segments in smaller chunks. But that seems like a lot of work for questionable benefit. Plus it'd work at sort of wrong level too (in XML token stream, before becoming values).

So perhaps it may be necessary to just document which format backends do support `StreamReadConstraints`, in `README.md` of this and other dataformat repos.
