### ISSUE TITLE
Unexpected curly braces when calling writeStartObject()

### ISSUE THREAD

**Issue by ian1dunn** [FasterXML/jackson-dataformat-xml#595]
Version: 2.14.2

I am in the beginnings of creating a custom serializer for a class (the entire serializer needs to be custom made due to the nature of the application) and ran into the following issue where `ToXmlGenerator.writeStartObject()` and  `ToXmlGenerator.writeEndObject()` write curly braces to the file instead of the expected root element.

Here is the serializer method override which uses the `_initWithRootName()` method from #216 
```java
    @Override
    public void serialize(Store store, JsonGenerator jsonGenerator, SerializerProvider provider) throws IOException {
        ToXmlGenerator xmlGenerator = (ToXmlGenerator) jsonGenerator;
        _initWithRootName(xmlGenerator, new QName("root"));

        xmlGenerator.writeStartObject();
        xmlGenerator.writeStringField("test", "value");
        xmlGenerator.writeEndObject();
    }
``` 

Here is the output that results from serializing an instance of this class:
```xml
<?xml version='1.1' encoding='UTF-8'?>{<test>value</test>
}
```

**Comment by pjfanning** [comment]
@cowtowncoder I added a small section about DefaultXmlPrettyPrinter in https://github.com/FasterXML/jackson-dataformat-xml/wiki and created https://github.com/FasterXML/jackson-core/pull/1017

**Comment by cowtowncoder** [comment]
Some other notes:

* Use of "simple" pretty-printing works same as with JSON (mapper.writerWithDefaultPrettyPrinter().writeValueAsString()); (I'll add a note on Wiki)
* It'd nice to throw an exception if attempting to set `PrettyPrinter` that is NOT an `XmlPrettyPrinter` on `XmlFactory` or `ToXmlGenerator` (assuming this is not happening currently).
