### ISSUE TITLE
Entity Encoding in Strings

### ISSUE THREAD

**Issue by AlanFoster** [FasterXML/jackson-dataformat-xml#61]
Hi all,

Thank you for this great plugin, it seems good nice so far!

I have been running into some issues with the entity encoding

Here is the code I've been testing out

``` java
package foo.bar;

import com.fasterxml.jackson.databind.ObjectWriter;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import org.junit.Test;

import java.io.IOException;
import java.io.Serializable;

public class JacksonEndpointTest {

    @Test
    public void serializeFailTest() throws Exception {
        String expectedXmlContentValue = "<Test />";

        XmlContainer xmlContainer = new XmlContainer();
        xmlContainer.setXmlContent(expectedXmlContentValue);

        String xmlContainerAsString = xmlContainer.toString();

        System.out.println("Xml Container as string :: " + xmlContainerAsString);
    }

    public static class XmlContainer implements Serializable {
        private String xmlContent;

        public void setXmlContent(String xmlContent) {
            this.xmlContent = xmlContent;
        }

        @Override
        public String toString() {
            XmlMapper xmlMapper = new XmlMapper();
            ObjectWriter writer = xmlMapper.writerWithDefaultPrettyPrinter();
            String xmlString = null;
            try {
                xmlString = writer.writeValueAsString(this);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }

            return xmlString;
        }
    }
}
```

And here are some values i've been testing with

``` xml
<!-- Input = "<Test>" -->
<XmlContainer>
  <xmlContent>&lt;Test></xmlContent>
</XmlContainer>
```

``` xml
<!-- Input = "Test<<<<>>>>"-->
 <XmlContainer>
  <xmlContent>Test&lt;&lt;&lt;&lt;&gt;&gt;&gt;&gt;</xmlContent>
</XmlContainer>
```

``` xml
<!-- Input = "<<<<>>>>"-->
 <XmlContainer>
  <xmlContent>&lt;&lt;&lt;&lt;>>>></xmlContent>
</XmlContainer>
```

I'm not exactly sure what's happening, but I'm not sure if this is expected behavior or not :)

Cheers

**Comment by DatoBula** [comment]
Can I configure which characters must escape mapper?

**Comment by DenisKatic** [comment]
We still see this issue in version 2.9.8 and our solution was to manual escape xml characters
org.apache.commons.lang3.StringEscapeUtils.escapeXml(value)
and to apply the @JsonRawValue annotation on the getter method.

**Comment by cowtowncoder** [comment]
@dabulashvili Not through Jackson API, but underlying `XMLOutputFactory` instances often have means to specify different escaping. Woodstox, for example, does allow that. See for example:

https://github.com/FasterXML/woodstox/issues/41

(and links from there).

It would be nice if someone had time and interest to work on #75 which is about exposing such functionality via `CharacterEscapes` abstraction already used with JSON. But I don't have time at this point nor likely to have in near future so it would have to be someone else.

**Comment by haihoang202** [comment]
@DenisKatic I tried your suggestion with escaping first and then use @JsonRawValue and the escaped character works correctly. However there is missing break line between the previous tag. For example:

<A></A><B>&amp;<B>

Instead of 

<A></A>
<B>&amp;</B>

Do you see the same issue ? Thanks :)
