### ISSUE TITLE
xmlMapper.readValue(  xmlString , Bean.class ) for Single Boolean Value does not get the value defaults with false

### ISSUE THREAD

**Issue by sandeepGenz** [FasterXML/jackson-dataformat-xml#641]
Let say there is a class Bean.java

```
public class Bean{
    boolean isAlive();
}
```

and there is a xmlString which has the above isAlive field with the value , now i need to parse this xml and store it into a java object,

but when i do xmlMapper.readValue( xmlString , Bean.class); if the isAlive() field in xmlString is true , but after deserializing through this above code , the value taken from the xml defaults to false. hence noticed that for boolean values it always defaults to false.

**Comment by cowtowncoder** [comment]
Unfortunately description is not enough to know what is going on: we'd need more information: specifically XML input used; and also actual `Bean` definition -- there seems to be no setter or field to set `alive` to.
And finally, configuration of `XmlMapper` probably matters too so should be included.

**Comment by cowtowncoder** [comment]
Closing, need extra info to help.
