### ISSUE TITLE
Add mechanism to run JDK 17 (Records) tests optionally, similar to `jackson-databind`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-xml#671]
(note: offshoot from #517) 

Currently we cannot add test cases for Record-handling, in Jackson 2.x, due to JDK baseline being Java 8 still.
But there is a way to do this; used f.ex by `jackson-databind`.
This is relatively simple by:

1. Adding tests under `src/test-jdk17/java/`
2. Using specific Maven profile to conditionally include this test source directory if (and only if) running on JDK 17+

It'd be good to be able to add specific Records-with-XML test cases.

**Comment by cowtowncoder** [comment]
cc @JooHyukKim WDYT?

**Comment by JooHyukKim** [comment]
Yup, totatlly makes sense.
