### ISSUE TITLE
AsPropertyTypeDeserializer._deserializeTypedForId loses FromXmlParser class definition for "jp"

### ISSUE THREAD

**Issue by ShawnTuatara** [FasterXML/jackson-dataformat-xml#70]
There is a piece of logic:

```
    if (tb != null) { // need to put back skipped properties?
        jp = JsonParserSequence.createFlattened(tb.asParser(jp), jp);
    }
```

that when used with a FromXmlParser causes the jp to change to a basic JsonParserSequence and as such on following call to deser.deserialize(jp, ctxt) breaks as the deser is the WrapperHandlingDeserializer in the xml package. The deserialize() method needs a FromXmlParser.

**Comment by cowtowncoder** [comment]
Unfortunately can not reproduce without test: I believe a problem exists, but would need repro.
May be reopened (or re-filed) with one.
