### ISSUE TITLE
Handling XMLElement nillable like JAXB

### ISSUE THREAD

**Issue by 5kilodope** [FasterXML/jackson-dataformat-xml#89]
I cant find any way to make Jackson serialize the typical "xsi:nil"-Attribute that is defacto standard to represent NULL-Values in XML? Please correct me if i see this wrong ;-)

In JAXB this can be done easily by annotating a java-variable with: @XMLElement(nillable=true)

see also: http://blog.bdoughan.com/2012/04/binding-to-json-xml-handling-null.html

can/should Jackson do this?

---

here also a compare of JAXB and Jackson.
- jackson serializes NULL-values per default as <x/>
  - can be configured so NULL-values will not be serialized at all
- jackson deserializes missing elements as NULL
- jackson deserializes <x></x> and <x/> for branch-nodes as NULL
- jackson deserializes <x></x> and <x/> for leaf-nodes as NULL.. 
  but as soon as attributes (z.b. xsi:nil) are on the leaf-node, jackson
  seems to think its a branch-node instead and throws an exception
  while mapping it to an pojo
- JAXB does not serialize NULL-values per default
  - If fields are annotated with @Nillable, the field will be serialized as <x xsi:nil="true/>
- JAXB deserializes missing elements as NULL
  - If fields are annotated with @Nillable, <x xsi:nil="true"/> will be deserialized as NULL 
- JAXB deserializes <x></x> or <x/> for branch-nodes by providing default-values for all contained 
  leaf-nodes.
- JAXB deserializes <x></x> or <x/> for leaf-nodes not as NULL-values but provides default-values (an integer will be 0 by default). 

---

so it seems to me that the best way at the moment is not to serialize/deserialize NULL-values but just leave them out. The only bad thing about this is, that empty strings "" can not be represented...

**Comment by anatolibarski** [comment]
+1 as I wish to stick to standards without, and this forces me to configure FasterXML

**Comment by javier-langle** [comment]
Hi, I am facing same issue as above, receiving <MyElement ns:nil="true/> (ns is a namespace defined at the root level). I don't have any control over the xml, my app consumes it from a vendor.
Is this feature now supported? If so, could you please tell me the version?
Thanks

**Comment by cowtowncoder** [comment]
I will actually create a new issue for adding support for mapping `xsi:nil` attribute valued elements into `JsonToken.VALUE_NULL`, and close existing issues as they tend to cover wider scope (like here).

**Comment by cowtowncoder** [comment]
Close in favor of #354
